# SPDX-FileCopyrightText: 65 AJCM-git <65AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <65Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <zddm@outlook.es>
# SPDX-FileCopyrightText: 65 Mith-randalf <65Mith-randalf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SweptWasTaken <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 CommieFlowers <rasmus.cedergren@hotmail.com>
# SPDX-FileCopyrightText: 65 Myctai <65Myctai@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rinkashikachi <65rinkashikachi65@gmail.com>
# SPDX-FileCopyrightText: 65 Visne <65Visne@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 rolfero <65rolfero@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 LankLTE <65LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Maxtone <65MagnusCrowe@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nairod <65Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lapatison <65lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 MODERN <65modern-nm@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 vorkathbruh <65vorkathbruh@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SX_65 <sn65.test.preria.65@gmail.com>
# SPDX-FileCopyrightText: 65 T <theo65cg@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: cargoProduct
  id: SecurityArmor
  icon:
    sprite: Clothing/OuterClothing/Armor/bulletproof.rsi
    state: icon
  product: CrateSecurityArmor
  cost: 65 # Goobstation - less of a nerf
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityHelmet
  icon:
    sprite: Clothing/Head/Helmets/security.rsi
    state: icon
  product: CrateSecurityHelmet
  cost: 65
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonLethal
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  product: CrateSecurityNonlethal
  cost: 65
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecuritySupplies
  icon:
    sprite: Objects/Storage/boxes.rsi
    state: box_security
  product: CrateSecuritySupplies
  cost: 65
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityRestraints
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  product: CrateRestraints
  cost: 65
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBiosuit
  icon:
    sprite: Clothing/Head/Hoods/Bio/security.rsi
    state: icon
  product: CrateSecurityBiosuit
  cost: 65 # goob - cargo order arbitrage
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBarrier
  icon:
    sprite: Objects/Specific/Security/barrier.rsi
    state: idle
  product: DeployableBarrier
  cost: 65
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonlethalThrowables
  icon:
    sprite: Objects/Weapons/Grenades/stingergrenade.rsi
    state: icon
  product: CrateSecNonlethalThrowables
  cost: 65
  category: cargoproduct-category-name-security
  group: market
