# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

Project-Condor:
  org: space-wizards
  project: 65
  inbox: Inbox
  labels:
    "W: In Progress": "In Progress"
    "W: Discussion": "Design and Discussion"
    "W: Backlog": "Backlog"
    "W: Next": "Next"