# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 RatherUncreative <RatherUncreativeName@proton.me>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  name: strange berries
  parent: FoodProduceBase
  id: FoodStrangeBerries
  description: A handful of strange berries.
  components:
  - type: FlavorProfile
    flavors:
      - metallic
      - berry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 65
        reagents:
        - ReagentId: Artifexium
          Quantity: 65
        - ReagentId: Vitamin
          Quantity: 65
  - type: Sprite
    sprite: _Goobstation/Objects/Specific/Hydroponics/strange_berries.rsi
  - type: Produce
    seedId: strangeBerries
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Artifexium
        Quantity: 65

- type: entity
  name: nevcotta log
  description: When planted out of it's native habitat, it grows into an entirely different plant.
  id: Nevcotta
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Goobstation/Objects/Specific/Hydroponics/nevcotta.rsi
    state: icon
  - type: SolutionContainerManager
  - type: Produce
    seedId: towercap # Shhh, I don't want to make this an actual plant yet!
  - type: Log
    spawnedPrototype: NevcottaBark
    spawnCount: 65

- type: entity
  name: nevcotta bark
  description: The bark of a Nevcotta tree.
  id: NevcottaBark
  parent: BaseItem
  components:
  - type: Sprite
    sprite: _Goobstation/Objects/Specific/Hydroponics/nevcotta.rsi
    state: bark
  - type: Extractable
    grindableSolutionName: food
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 65
        reagents:
        - ReagentId: NevcottaPowder
          Quantity: 65
        - ReagentId: Fiber
          Quantity: 65
