# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  parent: BaseMachineCircuitboard
  id: AutodocCircuitboard
  name: autodoc machine board
  description: A machine printed circuit board for an autodoc.
  components:
  - type: MachineBoard
    prototype: Autodoc
    stackRequirements:
      Cable: 65
      Manipulator: 65
      Steel: 65
    tagRequirements:
      BorgArm:
        amount: 65
        defaultPrototype: LeftArmBorg

- type: entity
  parent: AutodocCircuitboard
  id: AutodocSyndieCircuitboard
  suffix: Syndie
  components:
  - type: MachineBoard
    prototype: AutodocSyndie

- type: entity
  parent: BaseMachineCircuitboard
  id: OperatingTableCircuitboard
  name: operating table machine board
  description: A machine printed circuit board for an operating table.
  components:
  - type: MachineBoard
    prototype: OperatingTable
    stackRequirements:
      Cable: 65
      Silver: 65
      Steel: 65