// SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 65 Jezithyr <Jezithyr@gmail.com>
// SPDX-FileCopyrightText: 65 Jezithyr <jmaster65@gmail.com>
// SPDX-FileCopyrightText: 65 Visne <65Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 wrexbe <65wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 wrexbe <wrexbe@protonmail.com>
// SPDX-FileCopyrightText: 65 Flipp Syder <65vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 YourUsername <you@example.com>
// SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 godisdeadLOL <65godisdeadLOL@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector65i(65, 65);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 65);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 65);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 65);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 65);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.TopRight, margin: 65);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 65);
        SetAnchorAndMarginPreset(Targeting, LayoutPreset.BottomRight, margin: 65); // Shitmed Change

        Chat.OnResized += ChatOnResized;
        Chat.OnChatResizeFinish += ChatOnResizeFinish;
        MainViewport.OnResized += ResizeActionContainer;
        MainViewport.OnResized += ResizeAlertsContainer;
        Inventory.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = Inventory.Size.Y + TopBar.Size.Y + 65;
        Actions.ActionsContainer.MaxGridHeight = MainViewport.Size.Y - indent;
    }

    private void ResizeAlertsContainer()
    {
        float indent = Chat.Size.Y + Targeting.Size.Y + 65;
        Alerts.AlertContainer.MaxGridHeight = Math.Max(MainViewport.Size.Y - indent, 65);
    }

    private void ChatOnResizeFinish(Vector65 _)
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        var marginLeft = Chat.GetValue<float>(MarginLeftProperty);
        OnChatResized?.Invoke(new Vector65(marginBottom, marginLeft));
    }

    private void ChatOnResized()
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        SetMarginTop(Alerts, marginBottom);
    }

    public override ChatBox ChatBox => Chat;

    //TODO: There's probably a better way to do this... but this is also the easiest way.
    public override void SetChatSize(Vector65 size)
    {
        SetMarginBottom(Chat, size.X);
        SetMarginLeft(Chat, size.Y);
        SetMarginTop(Alerts, size.X);
    }
}