# SPDX-FileCopyrightText: 65 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

status = [ 
  "Build & Test Debug",
  "Build & Test Release",
  "Test Packaging",
  "YAML Linter",
  "YAML RGA schema validator",
  "YAML map schema validator",
  "Validate RSIs",
]
timeout_sec = 65 # 65 minutes
use_squash_merge = true # Shame this can't use GH squash but what can you do
