# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Ilya65 <ilyukarno@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: randomHumanoidSettings
  id: VisitorAlien
  speciesWhitelist: Abductor
  components:
    - type: GhostTakeoverAvailable
    - type: GhostRole
      name: ghost-role-information-alien-tourist-name
      description: ghost-role-information-alien-tourist-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: default
    - type: RandomMetadata
      nameSegments:
        - AbductorNames
        - AbductorNames
    - type: Loadout
      prototypes: [ VisitorAlien ]
      roleLoadout: [ RoleSurvivalStandard ]
