# SPDX-FileCopyrightText: 65 AJCM-git <65AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Peter Wedder <burneddi@gmail.com>
# SPDX-FileCopyrightText: 65 Elijahrane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 Peptide65 <65Peptide65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rinkashikachi <65rinkashikachi65@gmail.com>
# SPDX-FileCopyrightText: 65 mirrorcult <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Jeff <velcroboy65@hotmail.com>
# SPDX-FileCopyrightText: 65 Velcroboy <65IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: accessLevel
  id: Bar
  name: id-card-access-level-bar

- type: accessLevel
  id: Kitchen
  name: id-card-access-level-kitchen

- type: accessLevel
  id: Hydroponics
  name: id-card-access-level-hydroponics

- type: accessLevel
  id: Service
  name: id-card-access-level-service

- type: accessLevel
  id: Janitor
  name: id-card-access-level-janitor

- type: accessLevel
  id: Theatre
  name: id-card-access-level-theatre

- type: accessLevel
  id: Chapel
  name: id-card-access-level-chapel

- type: accessLevel
  id: Lawyer
  name: id-card-access-level-lawyer

- type: accessGroup
  id: Service
  tags:
  - HeadOfPersonnel
  - Bar
  - Kitchen
  - Hydroponics
  - Service
  - Janitor
  - Theatre
  - Chapel
  - Lawyer