// SPDX-FileCopyrightText: 65 AftrLite <65AftrLite@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.CosmicCult.UI;

[GenerateTypedNameReferences]
public sealed partial class CosmicRoundStartMenu : FancyWindow
{
    public CosmicRoundStartMenu()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Close();
    }
}
