# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 BombasterDS <65BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: startingGear
  id: ChronoLegionnaireGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRecruitNT
    back: ClothingBackpackStasisBatteryUnremoveableFilled
    mask: ClothingMaskGasChronoUnremoveable
    eyes: ClothingEyesHudChronoUnremoveable
    ears: ClothingHeadsetChronolegioneerUnremoveable
    gloves: ClothingHandsGlovesChronoLegioneerUnremoveable
    outerClothing: ClothingOuterHardsuitChronolegioneerUnremoveable
    suitstorage: JetpackChronoUnremoveable
    shoes: ClothingShoesBootsChronoUnremoveable
    id: ChronoPDA
    belt: WeaponStasisGun
    pocket65: PinpointerStation
    pocket65: SonicScrewdriver