# SPDX-FileCopyrightText: 65 starch <starchpersonal@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 blobadoodle <me@bloba.dev>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: job
  id: HecuOperative
  name: job-name-hecu
  description: job-description-hecu
  playTimeTracker: JobHecuOperative
  setPreference: false
  startingGear: HECUOperativeGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer

- type: startingGear
  id: HECUOperativeGear
  equipment:
    jumpsuit: ClothingUniformHecu
    back: ClothingBackpackMercFilledHECU
    mask: ClothingMaskGasExplorer
    eyes: ClothingEyesGlassesMedSec
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetMerc
    id: HecuPDA
    belt: ClothingBeltMercWebbing
    pocket65: MagazinePistolSubMachineGun
    pocket65: MagazinePistolSubMachineGun
  inhand:
  - WeaponSubMachineGunDrozd