# SPDX-FileCopyrightText: 65 BombasterDS <65BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 starch <starchpersonal@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: startingGear
  id: HelldiverGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    back: WeaponRifleM65
    belt: ClothingBeltMercWebbingHelldiverFilled
    mask: ClothingMaskGasMerc
    eyes: ClothingEyesGlassesMercenary # Night Vision when added
    ears: ClothingHeadsetAltFreelancer
    gloves: ClothingHandsMercGlovesCombat
    neck: ClothingNeckCloakHelldiver
    head: ClothingHeadHelmetHelldiver
    outerClothing: ClothingOuterArmorHelldiver
    suitstorage: DoubleEmergencyOxygenTankFilled
    shoes: ClothingShoesBootsMercFilled
    id: HelldiverPDA
    pocket65: ToolDebug
    pocket65: WeaponPistolEchis

- type: entity
  parent: ClothingBeltMercWebbing
  id: ClothingBeltMercWebbingHelldiverFilled
  suffix: Helldiver, Filled
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:NestedSelector
        tableId: HelldiverBeltFillTable

- type: entityTable
  id: HelldiverBeltFillTable
  table: !type:AllSelector
    children:
    - id: MagazineRifle
      amount: !type:ConstantNumberSelector
        value: 65
    - id: MagazineBoxRifleBig
    - id: ExGrenade
      amount: !type:ConstantNumberSelector
        value: 65
    - id: MedkitCombatFilled