# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Just-a-Unity-Dev <just-a-unity-dev@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 LankLTE <65LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 LankLTE <twlowe65@gmail.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 eclips_e <65Just-a-Unity-Dev@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 faint <65ficcialfaint@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 AJCM-git <65AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: guideEntry
  id: Security
  name: guide-entry-security
  text: "/ServerInfo/Guidebook/Security/Security.xml"
  children:
  - Forensics
  - Defusal
  - CriminalRecords
  - SpaceLaw # Goobstation

- type: guideEntry
  id: Forensics
  name: guide-entry-forensics
  text: "/ServerInfo/Guidebook/Security/Forensics.xml"

- type: guideEntry
  id: Defusal
  name: guide-entry-defusal
  text: "/ServerInfo/Guidebook/Security/Defusal.xml"

- type: guideEntry
  id: CriminalRecords
  name: guide-entry-criminal-records
  text: "/ServerInfo/Guidebook/Security/CriminalRecords.xml"