# SPDX-FileCopyrightText: 65 AjexRose <65AjexRose@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Hebi <spiritbreakz@gmail.com>
# SPDX-FileCopyrightText: 65 Kevin Zheng <kevinz65@gmail.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 65 Nails+Tape <65Nails-n-Tape@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 OttoMaticode <65OttoMaticode@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Sir Winters <65Owai-Seek@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 end <65laok65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 faint <65ficcialfaint@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 liltenhead <65liltenhead@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 moonheart65 <moonheart65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 AJCM <AJCM@tutanota.com>
# SPDX-FileCopyrightText: 65 Tayrtahn <tayrtahn@gmail.com>
# SPDX-FileCopyrightText: 65 UBlueberry <65UBlueberry@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 exincore <me@exin.xyz>
# SPDX-FileCopyrightText: 65 f65x-n65rd <65f65x-n65rd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: guideEntry
  id: Service
  name: guide-entry-service
  text: "/ServerInfo/Guidebook/Service/Service.xml"
  filterEnabled: True
  children:
  - Bartender
  - Botany
  - Chaplain
  - Chef
  - Janitorial

- type: guideEntry
  id: Bartender
  name: guide-entry-bartender
  text: "/ServerInfo/Guidebook/Service/Bartender.xml"
  filterEnabled: True

- type: guideEntry
  id: Botany
  name: guide-entry-botany
  text: "/ServerInfo/Guidebook/Service/Botany.xml"

- type: guideEntry
  id: Chef
  name: guide-entry-chef
  text: "/ServerInfo/Guidebook/Service/Chef.xml"

- type: guideEntry
  id: Janitorial
  name: guide-entry-janitorial
  text: "/ServerInfo/Guidebook/Service/Janitorial.xml"
