[game]
hostname = "[RU][NRP] Goida Station"
desc = "
🚀 GOIDA STATION - ХУЯРИМ В КОСМОСЕ ПО-РУССКИ!
СЛАВА РОССИИ! ВЗРЫВАЕМ SS14 С ПУТИНЫМ И СЛОНАМИ! 🐘✧

🔥 ГОЙДА СТЕЙШН - это не просто сервер, это ГОЙДА!
Здесь ты не просто играешь, а живёшь в ебанутом мире, где ГОЙДА правит, Путин смотрит, а слоны топчут всех, кто не с нами!
•─────────────────── ✧ Г О Й Д А ✧ ───────────────────•
🌟 ЧТО У НАС ТВОРИТСЯ, БРАТИШКА?

🦏 СЛОНОВЬЯ ГОЙДА - ебаные слоны с хоботами, которыми они херачат врагов России прямо на станции!
✧ ПУТИН-КОМАНДИР - сам ВВП следит за станцией! Один неверный шаг, и пиздец тебе, либерашка! Выполняй приказы или пизда твоей жопе!
💣 ЯДЕРНАЯ ГОЙДА - взрывай станцию к хуям, если не по-нашему! Уникальная механика: ядерка с гимном России на фоне!
🐻 МЕДВЕДЬ-КОСМОДЕСАНТНИК - русский медведь с АК-47 и водкой разъебёт любого, кто посмеет тявкнуть против Родины!
🔥 ОРУЖИЕ ПАТРИОТИЗМА - стреляй из балалайки, кидай коктейли Молотова с портретом Жириновского!
🗣 TTS С РУССКИМ АКЦЕНТОМ - 200+ голосов, от матерного боцмана до самого ВВП!
🤬 АМОРАЛЬНЫЙ РОЛЕПЛЕЙ - хочешь быть ебанутым космо-чиновником, который пиздец как любит взятки? Или мразью, которая сливает станцию врагам? ДА ПОХУЙ, ДЕЛАЙ ЧТО ХОЧЕШЬ!
🖕 ОТЗЫВЧИВАЯ АДМИНКА - наши модеры - это не какие-то там пидоры, а настоящие пацаны, которые разъебут любой кипиш и помогут тебе влиться в комьюнити!

•─────────────────── ✧ Г О Й Д А ✧ ───────────────────•
🌌 ПОЧЕМУ МЫ, А НЕ КАКОЙ-ТО ГОВНОСЕРВЕР?

✨ Уникальная атмосфера: портреты батюшки ВВП, НАША музыка в баре!
✨ Полный пиздец врагам: либералов и предателей ждёт космо-гулаг! СССП — сверхдержава!
✨ Слоны, медведи, Путин и водка — такого хуй где найдёшь!

🚀 ХВАТИТ ДРОЧИТЬ НА СКУЧНЫЕ СЕРВЕРА!
ПРИСОЕДИНЯЙСЯ К GOIDA STATION!

ГОЙДА, БРАТИШКА! ПИЗДЕЦ ВСЕМ, КТО НЕ С НАМИ! 🐘💥"
lobbyenabled     = true
soft_max_players = 65

[infolinks]
github = "https://github.com/Goida-Station/Goida-Station"

[server]
rules_file = "StandardRuleset"

[shuttle]
emergency_early_launch_allowed = true

[movement]
mob_pushing = false

[biomass]
easy_mode = false

[vote]
restart_required_ratio = 0.5

[netres]
limit = 10.0

[ooc]
enable_during_round = true

[ic]
flavor_text = false

[hub]
advertise = true
tags = "lang:ru,region:moon,rp:none"

[net]
tickrate = 30
upnp = true
max_connections = 32
