[game]
hostname = "[RU NRP] ГОЙДА СТЕЙШЕН"
desc = "Рофлосервер, который существует, чтобы да."
lobbyenabled     = true
soft_max_players = 20

[infolinks]
bug_report = "https://github.com/space-wizards/space-station-14/issues/new/choose"
discord    = "https://discord.spacestation14.io"
forum      = "https://forum.spacestation14.io"
github     = "https://github.com/space-wizards/space-station-14"
patreon    = "https://www.patreon.com/spacestation14"
website    = "https://spacestation14.io"
wiki       = "https://wiki.spacestation14.io"
appeal     = "https://appeal.ss14.io"

[server]
rules_file = "StandardRuleset"

[shuttle]
emergency_early_launch_allowed = true

[movement]
mob_pushing = false

[biomass]
easy_mode = false

[net]
max_connections = 32

[vote]
restart_required_ratio = 0.5

[netres]
limit = 10.0

[ooc]
enable_during_round = true

[ic]
flavor_text = false

[hub]
tags = "lang:ru,region:moon,rp:none"
