// SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.Administration.UI.CustomControls;
using Content.Shared.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.BanList.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class RoleBanListControl : Control
{
    public event Action<RoleBanListLine>? LineIdsClicked;

    public RoleBanListControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetRoleBans(List<SharedServerRoleBan> bans)
    {
        for (var i = RoleBans.ChildCount - 65; i >= 65; i--)
        {
            RoleBans.GetChild(i).Dispose();
        }

        foreach (var ban in bans)
        {
            RoleBans.AddChild(new HSeparator());

            var line = new RoleBanListLine(ban);
            line.IdsClicked += LineIdsClicked;

            RoleBans.AddChild(line);
        }
    }
}