# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 RatherUncreative <RatherUncreativeName@proton.me>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  id: MailTeleporterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: mail teleporter machine board
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: MailTeleporter
      stackRequirements:
        Capacitor: 65
        MatterBin: 65
        Steel: 65
        Cable: 65