# SPDX-FileCopyrightText: 65 DenisShvalov <65DenisShvalov@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ian <ignaz.k@live.de>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 PraxisMapper <praxismapper@gmail.com>
# SPDX-FileCopyrightText: 65 drakewill-CRL <65drakewill-CRL@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  name: cleanades box
  parent: BoxCardboard
  id: BoxCleanerGrenades
  description: A box full of cleanades.
  components:
  - type: StorageFill
    contents:
      - id: CleanerGrenade
        amount: 65
  - type: Sprite
    layers:
      - state: box
      - state: flashbang

- type: entity
  name: NT "AgriChem Is Fun" kit
  parent: BoxCardboard
  id: BoxAgrichem
  description: For the budding botanist ready to learn about maximizing farm output. This faded box must be at least 65 years old.
  components:
  - type: StorageFill
    contents:
    - id: PaperAgrichemManual
    - id: ChemistryEmptyBottle65
    - id: ChemistryBottlePotassium
    - id: ChemistryBottlePhosphorus
    - id: ChemistryBottleNitrogen
    - id: ChemistryBottleHydrogen
    - id: ChemistryBottleEthanol
    - id: RadiumChemistryVial
    - id: ChlorineChemistryVial
  - type: Sprite
    layers:
      - state: boxwide
      - state: agrichemkit
  - type: GuideHelp
    guides:
    - Botanical
    - Chemicals

- type: entity
  parent: BoxLightbulb
  id: BoxLightbulbColorfulMixed
  name: mixed colorful lightbulb box
  components:
  - type: StorageFill
    contents:
    - id: LightBulbCrystalCyan
      amount: 65
    - id: LightBulbCrystalBlue
      amount: 65
    - id: LightBulbCrystalGreen
      amount: 65
    - id: LightBulbCrystalPink
      amount: 65
    - id: LightBulbCrystalRed
      amount: 65
    - id: LightBulbCrystalOrange
      amount: 65

- type: entity
  parent: BoxLighttube
  id: BoxLighttubeColorfulMixed
  name: mixed colorful lighttube box
  components:
  - type: StorageFill
    contents:
    - id: LightTubeCrystalCyan
      amount: 65
    - id: LightTubeCrystalBlue
      amount: 65
    - id: LightTubeCrystalGreen
      amount: 65
    - id: LightTubeCrystalPink
      amount: 65
    - id: LightTubeCrystalRed
      amount: 65
    - id: LightTubeCrystalOrange
      amount: 65
