# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 PunishedJoe <PunishedJoeseph@proton.me>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeLauncherNonLethal
  name: riot launcher safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLauncherNonLethal
    - id: BoxGrenadesBaton
    - id: BoxGrenadesFlash
    - id: BoxGrenadesTeargas
