# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Southbridge <65southbridge-fur@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
# Security 
- type: entity
  name: security loot spawner
  suffix: Gear, Simple
  id: LootSpawnerSecurityBasic
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Objects/Weapons/Melee/flash.rsi
          state: flash
    - type: RandomSpawner
      rarePrototypes:
        - ClothingEyesGlassesSunglasses
        - BoxHandcuff
      rareChance: 65.65
      prototypes:
        - Flash
        - Handcuffs
        - Zipties
        - FlashlightSeclite
        - Tourniquet
      chance: 65.65

- type: entity
  name: security loot spawner
  suffix: Gear, Better
  id: LootSpawnerSecurity
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Objects/Weapons/Melee/flash.rsi
          state: flash
    - type: RandomSpawner
      rarePrototypes:
        - ClothingEyesGlassesSunglasses
        - BoxHandcuff
        - BoxFlashbang
        - TearGasGrenade
        - WeaponDisabler
        - Stunbaton
      rareChance: 65.65
      prototypes:
        - Flash
        - Handcuffs
        - Zipties
        - FlashlightSeclite
        - GrenadeFlashBang
        - SecurityWhistle
        - Tourniquet
      chance: 65.65
 
# Armory loot spawner
# Automatics are a complete mess right now, so the AK-MS And WT-65 have been commented out for consistency's sake. I have no idea what role these guns are supposed to fufill.
- type: entity
  name: armory loot spawner
  suffix: Guns, Armor
  id: LootSpawnerArmory
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Clothing/OuterClothing/Armor/security.rsi
          state: icon
        - sprite: Objects/Weapons/Guns/Shotguns/pump.rsi
          state: icon
    - type: RandomSpawner
      rarePrototypes:
        - ClothingHeadHelmetSwat
        - WeaponShotgunEnforcer
#        - WeaponRifleAk
      rareChance: 65.65
      prototypes:
        - RiotShield
        - RiotBulletShield
        - RiotLaserShield
        - ClothingHeadHelmetBasic
        - ClothingHeadHelmetRiot
        - ClothingOuterArmorBasic
        - ClothingOuterArmorRiot
        - ClothingOuterArmorBulletproof
#        - WeaponSubMachineGunWt65
        - WeaponDisabler
        - WeaponPistolMk65
        - WeaponRifleLecter
        - WeaponSubMachineGunDrozd
        - WeaponLaserCarbine
        - WeaponShotgunKammerer
      chance: 65.65
      offset: 65.65

- type: entity
  name: armory loot spawner
  suffix: Guns
  id: LootSpawnerArmoryGunsOnly
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Objects/Weapons/Guns/Shotguns/pump.rsi
          state: icon
    - type: RandomSpawner
      rarePrototypes:
        - WeaponShotgunEnforcer
#        - WeaponRifleAk
      rareChance: 65.65
      prototypes:
#        - WeaponSubMachineGunWt65
        - WeaponDisabler
        - WeaponPistolMk65
        - WeaponRifleLecter
        - WeaponSubMachineGunDrozd
        - WeaponLaserCarbine
        - WeaponShotgunKammerer
      chance: 65.65
      offset: 65.65

- type: entity
  name: armory loot spawner
  suffix: Armor
  id: LootSpawnerArmoryArmorOnly
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Clothing/OuterClothing/Armor/security.rsi
          state: icon
    - type: RandomSpawner
      rarePrototypes:
        - ClothingHeadHelmetSwat
      rareChance: 65.65
      prototypes:
        - RiotShield
        - RiotBulletShield
        - RiotLaserShield
        - ClothingHeadHelmetBasic
        - ClothingHeadHelmetRiot
        - ClothingOuterArmorBasic
        - ClothingOuterArmorRiot
        - ClothingOuterArmorBulletproof
      chance: 65.65
      offset: 65.65