# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Visne <65Visne@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/space-wizards/space-station-65/blob/master/SECURITY.md
    about: Please report security vulnerabilities privately so we can fix them before they are publicly disclosed.
  - name: Request a Feature
    url: https://discord.gg/rGvu65hKffJ
    about: Submit feature requests on our Discord server (https://discord.gg/rGvu65hKffJ).