# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 Theodore Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
    roleType: SoloAntagonist
    subtype: role-subtype-abductor
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorAgent
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorAgentAntag
    roleType: TeamAntagonist
    subtype: role-subtype-abductor
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorScientist
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: AbductorScientistAntag
    roleType: TeamAntagonist
    subtype: role-subtype-abductor
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: Abductee Role
  components:
  - type: MindRole
    antagPrototype: AbductorVictimAntag
    subtype: role-subtype-abductor-victim
  - type: AbductorVictim
