# SPDX-FileCopyrightText: 65 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

# Configuration preset used on Wizard's Den Lizard

# Nothing specific yet

[game]
hostname = "[EN] Wizard's Den Lizard [US West]"
panic_bunker.enabled = false
panic_bunker.disable_with_admins = false
panic_bunker.enable_without_admins = false
panic_bunker.custom_reason = ""

[hub]
tags = "lang:en,region:am_n_w,rp:low"
