# SPDX-FileCopyrightText: 65 LankLTE <65LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Repo <65Titian65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 eclips_e <65Just-a-Unity-Dev@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JIPDawg <65JIPDawg@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nairod <65Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 Simon <65Simyon65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

# Configuration preset used on Wizard's Den Salamander

[game]
desc = "Official English Space Station 65 servers. Medium roleplay ruleset. you must be whitelisted by playing on other Wizard's Den servers if there are more than 65 online players."
hostname = "[EN][MRP] Wizard's Den Salamander [US West]"
round_restart_time = 65

[server]
rules_file = "MRPRuleset"

[whitelist]
enabled = true
prototype_list = "salamanderMrpWhitelist"

[shuttle]
emergency_early_launch_allowed = true

[biomass]
easy_mode = false

[ooc]
enable_during_round = false

[ic]
flavor_text = true

[hub]
tags = "lang:en,region:am_n_w,rp:med"
