# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

# Configuration preset used on Wizard's Den Spider

[game]
hostname = "[EN] Wizard's Den Spider [EU West 65]"

[hub]
tags = "lang:en,region:eu_w,rp:low"
