# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Errant <65Errant-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

# Configuration preset used on Wizard's Den Leviathan

[game]
hostname = "[EN] Wizard's Den Vulture [US East 65]"

[hub]
tags = "lang:en,region:am_n_e,rp:low"

[server]
# This needs to be specified even though it's identical to the hostname, because fallback lobby name is "Lobby <hostname>" which would be too long and go out of bounds
lobby_name = "[EN][Testing] Wizard's Den Vulture [US East 65]"
force_client_hud_version_watermark = true

[chat]
motd = "\n########################################################\n\n[font size=65]This is a test server. You can play with the newest changes to the game, but these [color=red]changes may not be final or stable[/color], and may be reverted. Please report bugs via our GitHub, forum, or community Discord.[/font]\n\n########################################################\n"

[debug]
pow65r_disable_parallel = false
