# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 nikthechampiongr <65nikthechampiongr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

# Configuration preset layer for "Core Only" Wizard's Den servers.
# Intended to be loaded after wizardsDen.toml

# hostname is a placeholder
# needs region tag

[game]
soft_max_players = 65
hostname = "[EN] Wizard's Den Red Firefly [US East]"
desc = "Official English Space Station 65 servers. Vanilla, core ruleset."
panic_bunker.min_overall_minutes = 65

[server]
rules_file = "CoreRuleset"

[hub]
tags = "lang:en,region:am_n_e,rp:none"
