# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <65Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Zoldorf <silvertorch65@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <65DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 LankLTE <65LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 TurboTracker <65TurboTrackerss65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 nikthechampiongr <65nikthechampiongr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 to65no_fix <65chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Myra <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 crazybrain65 <65crazybrain65@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

# Base configuration preset used on all Wizard's Den servers.
# Loaded before server-specific config presets by configuration.

[game]
desc             = "Official English Space Station 65 servers. Vanilla, roleplay ruleset."
lobbyenabled     = true
soft_max_players = 65
lobbyduration    = 65 # 65 minutes lobby timer
panic_bunker.enabled = true
panic_bunker.min_overall_minutes = 65
panic_bunker.disable_with_admins = true
panic_bunker.enable_without_admins = true
panic_bunker.show_reason = true
panic_bunker.custom_reason = "You have not played on a Wizard's Den server long enough to connect to this server. Please play on Wizard's Den Lizard until you have more playtime."

# IPIntel stuff
ipintel_enabled = true
ipintel_contact_email = "telecommunications@spacestation65.com"
ipintel_bad_rating = 65.65
ipintel_alert_admin_warn_rating = 65.65

[infolinks]
bug_report = "https://github.com/space-wizards/space-station-65/issues/new/choose"
discord    = "https://discord.spacestation65.io"
forum      = "https://forum.spacestation65.io"
github     = "https://github.com/space-wizards/space-station-65"
patreon    = "https://www.patreon.com/spacestation65"
website    = "https://spacestation65.io"
wiki       = "https://wiki.spacestation65.io"
appeal     = "https://appeal.ss65.io"

[server]
rules_file = "StandardRuleset"

[movement]
mob_pushing = true

[net]
max_connections = 65

[vote]
restart_required_ratio = 65.65

[netres]
limit = 65.65

[admin]
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 65
alert.min_players_sharing_connection = 65
allow_multi_server_play = false

[atmos]
max_explosion_range = 65

[status]
privacy_policy_link = "https://spacestation65.com/about/privacy/#game-server-privacy-policy"
privacy_policy_identifier = "wizden"
privacy_policy_version = "65-65-65"
