# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SETh lafuente <cetaciocascarudo@gmail.com>
# SPDX-FileCopyrightText: 65 SethLafuente <65SethLafuente@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 SweptWasTaken <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 Tarlan65 <65Tarlan65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <gradientvera@outlook.com>
# SPDX-FileCopyrightText: 65 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Peptide65 <65Peptide65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ripmorld <65UKNOWH@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <65DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <le65nel_65van@hotmail.com>
# SPDX-FileCopyrightText: 65 ZeroDayDaemon <65ZeroDayDaemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 keronshb <65keronshb@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 65 Boaz65 <65Boaz65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Gagarinten-Noverdo <65noverd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 HerCoyote65 <65HerCoyote65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kevin Zheng <kevinz65@gmail.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 65 Nim <65Nimfar65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Puro <65PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Scribbles65 <65Scribbles65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Stanislav65ix <65Stanislav65ix@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vordenburg <65Vordenburg@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Whisper <65QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 chromiumboy <65chromiumboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lapatison <65lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 liltenhead <65liltenhead@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Alzore <65Blackern65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 BramvanZijp <65BramvanZijp@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Cojoke <65Cojoke-dot@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ghagliiarghii <65Ghagliiarghii@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GitHubUser65 <65GitHubUser65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nairod <65Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <plykiya@protonmail.com>
# SPDX-FileCopyrightText: 65 SlamBamActionman <slambamactionman@gmail.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 icekot65 <65icekot65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 takemysoult <65takemysoult@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 to65no_fix <65chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Milon <milonpl.git@proton.me>
# SPDX-FileCopyrightText: 65 SX_65 <sn65.test.preria.65@gmail.com>
# SPDX-FileCopyrightText: 65 āda <ss.adasts@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseWeaponRecipe
  categories:
  - Weapons
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  abstract: true
  parent: BaseWeaponRecipe
  id: BaseWeaponRecipeLong
  completetime: 65

- type: latheRecipe
  abstract: true
  id: BaseAmmoRecipe
  categories:
  - Ammo
  completetime: 65

- type: latheRecipe
  abstract: true
  parent: BaseAmmoRecipe
  id: BaseEmptyAmmoRecipe
  completetime: 65

# Recipes

- type: latheRecipe
  id: Handcuffs
  result: Handcuffs
  completetime: 65
  materials:
    Steel: 65

- type: latheRecipe
  id: Zipties
  result: Zipties
  completetime: 65
  materials:
    Plastic: 65

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Stunbaton
  result: Stunbaton

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: Truncheon
  result: Truncheon

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: CombatKnife
  result: CombatKnife
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCarbine
  result: WeaponLaserCarbine
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponAdvancedLaser
  result: WeaponAdvancedLaser
  materials:
    Steel: 65
    Glass: 65
    Gold: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCannon
  result: WeaponLaserCannon
  materials:
    Steel: 65
    Plastic: 65
    Gold: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserSvalinn
  result: WeaponLaserSvalinn
  materials:
    Steel: 65
    Gold: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponXrayCannon
  result: WeaponXrayCannon
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65
    Gold: 65

- type: latheRecipe
  id: ClothingBackpackElectropack
  result: ClothingBackpackElectropack
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Cloth: 65

- type: latheRecipe
  id: ForensicPad
  result: ForensicPad
  completetime: 65
  materials:
    Plastic: 65

- type: latheRecipe
  id: ClothingEyesHudSecurity
  result: ClothingEyesHudSecurity
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: HoloprojectorSecurity
  result: HoloprojectorSecurityEmpty
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  id: RiotShield
  result: RiotShield
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: TelescopicShield
  result: TelescopicShield
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: Flash
  result: Flash
  completetime: 65
  materials:
    Glass: 65
    Plastic: 65
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShellTranquilizer
  result: BoxShellTranquilizer
  materials:
    Plastic: 65
    Steel: 65
    Glass: 65
    Plasma: 65
    Silver: 65

- type: latheRecipe
  id: TargetHuman
  result: TargetHuman
  completetime: 65
  applyMaterialDiscount: false # ingredients dropped when destroyed
  materials:
    Steel: 65

- type: latheRecipe
  parent: TargetHuman
  id: TargetClown
  result: TargetClown

- type: latheRecipe
  parent: TargetHuman
  id: TargetSyndicate
  result: TargetSyndicate

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolEmpty
  result: MagazinePistolEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol
  result: MagazinePistol
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolPractice
  result: MagazinePistolPractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolUranium
  result: MagazinePistolUranium
  materials:
    Steel: 65
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolIncendiary
  result: MagazinePistolIncendiary
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolSubMachineGunEmpty
  result: MagazinePistolSubMachineGunEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGun
  result: MagazinePistolSubMachineGun
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunUranium
  result: MagazinePistolSubMachineGunUranium
  materials:
    Steel: 65
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunIncendiary
  result: MagazinePistolSubMachineGunIncendiary
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolSubMachineGunTopMountedEmpty
  result: MagazinePistolSubMachineGunTopMountedEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunTopMounted
  result: MagazinePistolSubMachineGunTopMounted
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistol
  result: MagazineBoxPistol
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnum
  result: MagazineBoxMagnum
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineRifleEmpty
  result: MagazineRifleEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle
  result: MagazineRifle
  materials:
    Steel: 65


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRiflePractice
  result: MagazineRiflePractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleUranium
  result: MagazineRifleUranium
  materials:
    Steel: 65
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleIncendiary
  result: MagazineRifleIncendiary
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineLightRifleEmpty
  result: MagazineLightRifleEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifle
  result: MagazineLightRifle
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRiflePractice
  result: MagazineLightRiflePractice
  materials:
    Steel: 65


- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleUranium
  result: MagazineLightRifleUranium
  materials:
    Steel: 65
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleIncendiary
  result: MagazineLightRifleIncendiary
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifle
  result: MagazineBoxRifle
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifle
  result: MagazineBoxLightRifle
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxLethalshot
  result: BoxLethalshot
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxBeanbag
  result: BoxBeanbag
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunSlug
  result: BoxShotgunSlug
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: SpeedLoaderMagnumEmpty
  result: SpeedLoaderMagnumEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnum
  result: SpeedLoaderMagnum
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumPractice
  result: SpeedLoaderMagnumPractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumUranium
  result: SpeedLoaderMagnumUranium
  materials:
    Steel: 65
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumIncendiary
  result: SpeedLoaderMagnumIncendiary
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineShotgunEmpty
  result: MagazineShotgunEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgun
  result: MagazineShotgun
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunBeanbag
  result: MagazineShotgunBeanbag
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunSlug
  result: MagazineShotgunSlug
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunIncendiary
  result: MagazineShotgunIncendiary
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolIncendiary
  result: MagazineBoxPistolIncendiary
  materials:
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumIncendiary
  result: MagazineBoxMagnumIncendiary
  materials:
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleIncendiary
  result: MagazineBoxLightRifleIncendiary
  materials:
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleIncendiary
  result: MagazineBoxRifleIncendiary
  materials:
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunFlare
  result: BoxShotgunFlare
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunIncendiary
  result: BoxShotgunIncendiary
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolPractice
  result: MagazineBoxPistolPractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumPractice
  result: MagazineBoxMagnumPractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRiflePractice
  result: MagazineBoxLightRiflePractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRiflePractice
  result: MagazineBoxRiflePractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLaserCarbinePractice
  result: WeaponLaserCarbinePractice
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisablerPractice
  result: WeaponDisablerPractice
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunPractice
  result: BoxShotgunPractice
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolUranium
  result: MagazineBoxPistolUranium
  materials:
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumUranium
  result: MagazineBoxMagnumUranium
  materials:
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxLightRifleUranium
  result: MagazineBoxLightRifleUranium
  materials:
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxRifleUranium
  result: MagazineBoxRifleUranium
  materials:
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BoxShotgunUranium
  result: BoxShotgunUranium
  materials:
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponFlareGunSecurity
  result: WeaponFlareGunSecurity
  completetime: 65
  materials:
    Plastic: 65
    Steel: 65

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponDisabler
  result: WeaponDisabler
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  parent: WeaponDisabler
  id: WeaponDisablerSMG
  result: WeaponDisablerSMG
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  id: MagazineGrenadeEmpty
  result: MagazineGrenadeEmpty
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  id: GrenadeEMP
  result: GrenadeEMP
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Glass: 65

- type: latheRecipe
  id: GrenadeBlast
  result: GrenadeBlast
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Gold: 65

- type: latheRecipe
  id: GrenadeFlash
  result: GrenadeFlash
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Glass: 65

- type: latheRecipe
  id: PortableRecharger
  result: PortableRecharger
  completetime: 65
  materials:
    Steel: 65
    Uranium: 65
    Plastic: 65
    Plasma: 65
    Glass: 65
