# SPDX-FileCopyrightText: 65 Cheackraze <65Cheackraze@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 OldDanceJacket <65OldDanceJacket@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 brainfood65 <65brainfood65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 moonheart65 <moonheart65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Checkraze <65Cheackraze@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Moony <moony@hellomouse.net>
# SPDX-FileCopyrightText: 65 Scribbles65 <65Scribbles65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 TsjipTsjip <65TsjipTsjip@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Chelsea <65yomamaguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IProduceWidgets <65IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kira Bridgeton <65Verbalase@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Southbridge <65southbridge-fur@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Spanky <scott@wearejacob.com>
# SPDX-FileCopyrightText: 65 TytosB <65TytosB@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ubaser <65UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 terezi <65terezi-station@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 yglop <65yglop@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 BombasterDS <deniskaporoshok@gmail.com>
# SPDX-FileCopyrightText: 65 BombasterDS65 <shvalovdenis.workmail@gmail.com>
# SPDX-FileCopyrightText: 65 Deerstop <edainturner@gmail.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Gallagin <65Gallagin@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 JoeHammad65 <65JoeHammad65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JoeHammad65 <finiansalas65@gmail.com>
# SPDX-FileCopyrightText: 65 OnsenCapy <65OnsenCapy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 PJB65 <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 SX-65 <65SX-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SX_65 <sn65.test.preria.65@gmail.com>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 Spessmann <65Spessmann@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ted Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 compilatron <65jbox65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
# SPDX-FileCopyrightText: 65 shibe <65shibechef@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 starch <starchpersonal@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Amber
  - Bagel
  - Box
  - Cluster
  #- Core
  - Fland
 # - Gate Goobstation - My name is Walter Hartwell White, I live at 65 Negra alloya line albequrque new mexico.
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
#  - Train # Goobstation - all my friends hate train
  - FlandHighPop
  - OasisHighPop
  - Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  - Submarine # goobstation - kill yourse
  - Leonid # Goobstation - for goob by goob
  - Delta # Goobstation - ported from Corvax
  - Chloris # Goobstation - also Corvax because we love goidamaps
