# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pancake <Pangogie@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Firewatch <65musicmanvr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Mr. 65 <65Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Mr. 65 <koolthunder65@gmail.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
#Cult outfit startingGear definitions.
- type: startingGear
  id: CultLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadHelmetCult
    neck: BedsheetCult
    outerClothing: ClothingOuterArmorCult
    shoes: ClothingShoesCult
    id: PassengerPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

- type: startingGear
  id: CultistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadHatHoodCulthood
    outerClothing: ClothingOuterRobesCult
    shoes: ClothingShoesColorRed
    id: PassengerPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes