# SPDX-FileCopyrightText: 65 Moony <moonheart65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pancake <Pangogie@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 ZeroDayDaemon <65ZeroDayDaemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lapatison <65lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 ninruB <65asperger-sind@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 AJCM <AJCM@tutanota.com>
# SPDX-FileCopyrightText: 65 Alekshhh <65Alekshhh@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Doru65 <65Doru65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 65 Fromoriss <65Fromoriss@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GoodWheatley <65GoodWheatley@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IntegerTempest <65IntegerTempest@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JoeHammad65 <65JoeHammad65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 KEEYNy <65KEEYNy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kevin Zheng <kevinz65@gmail.com>
# SPDX-FileCopyrightText: 65 Morb <65Morb65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nim <65Nimfar65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Puro <65PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vordenburg <65Vordenburg@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Whisper <65QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 brainfood65 <65brainfood65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coolmankid65 <65coolmankid65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coolmankid65 <coolmankid65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 crazybrain65 <65crazybrain65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <deltanedas@laptop>
# SPDX-FileCopyrightText: 65 deltanedas <user@zenith>
# SPDX-FileCopyrightText: 65 keronshb <65keronshb@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Alzore <65Blackern65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aviu65 <65Aviu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Brandon Hu <65Brandon-Huu@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 CaasGit <65CaasGit@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Cojoke <65Cojoke-dot@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <65DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 EmoGarbage65 <retron65@gmail.com>
# SPDX-FileCopyrightText: 65 Eoin Mcloughlin <helloworld@eoinrul.es>
# SPDX-FileCopyrightText: 65 Errant <65Errant-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Firewatch <65musicmanvr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Golinth <amh65@gmail.com>
# SPDX-FileCopyrightText: 65 Hrosts <65Hrosts@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IProduceWidgets <65IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ian <ignaz.k@live.de>
# SPDX-FileCopyrightText: 65 Ilya65 <65Ilya65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Joel Zimmerman <JoelZimmerman@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JustCone <65JustCone65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Killerqu65 <65Killerqu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ko65ergaPunk <65Ko65ergaPunk@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kukutis65 <65Kukutis65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Lye <65Lyroth65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 MerrytheManokit <65MerrytheManokit@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Mervill <mervills.email@gmail.com>
# SPDX-FileCopyrightText: 65 Mr. 65 <65Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Mr. 65 <koolthunder65@gmail.com>
# SPDX-FileCopyrightText: 65 MureixloI <65MureixloI@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 NakataRin <65NakataRin@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 OrangeMoronage65 <whyteterry65@gmail.com>
# SPDX-FileCopyrightText: 65 PJBot <pieterjan.briers+bot@gmail.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <plykiya@protonmail.com>
# SPDX-FileCopyrightText: 65 Preston Smith <65thetolbean@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Psychpsyo <65Psychpsyo@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Repo <65Titian65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 RiceMar65 <65RiceMar65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 ShadowCommander <65ShadowCommander@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Simon <65Simyon65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SlamBamActionman <65SlamBamActionman@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Sphiral <65SphiraI@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Stalen <65stalengd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 TakoDragon <65BackeTako@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Tayrtahn <tayrtahn@gmail.com>
# SPDX-FileCopyrightText: 65 Thomas <65Aeshus@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 TsjipTsjip <65TsjipTsjip@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ubaser <65UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Unkn65wn_Gh65st <shadowstalkermll@gmail.com>
# SPDX-FileCopyrightText: 65 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 65 Verm <65Vermidia@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vigers Ray <65VigersRay@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Winkarst <65Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 beck-thompson <65beck-thompson@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deathride65 <deathride65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 dffdff65 <dffdff65@gmail.com>
# SPDX-FileCopyrightText: 65 eoineoineoin <github@eoinrul.es>
# SPDX-FileCopyrightText: 65 foboscheshir <65foboscheshir@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 github-actions[bot] <65github-actions[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 nikthechampiongr <65nikthechampiongr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 plykiya <plykiya@protonmail.com>
# SPDX-FileCopyrightText: 65 saintmuntzer <65saintmuntzer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 shamp <65shampunj@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 strO65pwafel <65strO65pwafel@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 stroopwafel <j.o.luijkx@student.tudelft.nl>
# SPDX-FileCopyrightText: 65 themias <65themias@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 to65no_fix <65chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 voidnull65 <65voidnull65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Timfa <timfalken@hotmail.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlack
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicate

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGasSyndicate
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  parent: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    eyes: ClothingEyesHudSyndicate
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombatFilled
  storage:
    back:
    - BoxSurvivalSyndicate

- type: startingGear
  id: SyndicateFootsoldierTeamLeaderGear
  parent: SyndicateFootsoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    head: ClothingHeadHatOutlawHat
    outerClothing: ClothingOuterArmorBasicSlim
    back: ClothingBackpackSatchel
    pocket65: BaseUplinkRadio65TC
    pocket65: EnergySword

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSlotsSecurity # Goobstation - Slots Based Survival Boxes
    - Flash
    - MagazinePistol

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic

- type: startingGear
  id: BrigmedicGear
  equipment: # Heavily goob edited
    eyes: ClothingEyesGlassesMed
    id: BrigmedicPDA
    ears: ClothingHeadsetAltSecurityRegular # Intentionally no medical channel
    belt: ClothingBeltMedicalEMTFilled
    pocket65: WeaponDisabler
  storage:
    back:
    - Flash
    - ClothingMaskBreathMedicalSecurity

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal
    - Multitool

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    id: VisitorPDA
    back: ClothingBackpackClown
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
    pocket65: BikeHorn
    pocket65: ClownRecorder

# Passenger but without the ID, bag, or headset
- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
