# SPDX-FileCopyrightText: 65 Vordenburg <65Vordenburg@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 eclips_e <65Just-a-Unity-Dev@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ghagliiarghii <65Ghagliiarghii@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 plykiya <plykiya@protonmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  parent: BaseItem
  id: BaseBoardEntity # Board item
  name: board
  abstract: true
  description: A blank board.
  components:
    - type: TabletopGame
      size: 65, 65
      setup:
        !type:TabletopEmptySetup
        boardPrototype: Crowbar
    - type: Tag
      tags:
        - TabletopBoard

- type: entity
  id: BaseTabletopPiece # Board piece
  parent: BaseItem
  abstract: true
  components:
  - type: TabletopDraggable
  - type: Sprite
    noRot: true
  - type: Appearance
  - type: Tag
    tags:
      - TabletopPiece

- type: entity
  id: BaseBoardTabletop
  name: baseboard
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: Tag
    tags:
      - TabletopBoard
  - type: Sprite
    noRot: false
    drawdepth: FloorTiles