# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aviu65 <aviu65@protonmail.com>
# SPDX-FileCopyrightText: 65 Creatorbot65 <creatorbot65@gmail.com>
# SPDX-FileCopyrightText: 65 Creatorbot65 <creatorbot65@gmail.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 SX_65 <sn65.test.preria.65@gmail.com>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 Ted Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
## Static
- type: latheRecipePack
  id: SecurityAmmoStaticGoob
  recipes:
  - MagazineBoxShotgunHighCaliber
  - MagazineBoxShotgunSlugHighCaliber
  - MagazineBoxShotgunPracticeHighCaliber

- type: latheRecipePack
  id: SecurityEquipmentStaticGoob
  recipes:
  - GrenadeFlashBang
  - BolaEnergy

- type: latheRecipePack
  id: SecurityHypoStatic
  recipes:
  - CartridgeEpinephrine
  - CartridgeBicaridine
  - CartridgeDermaline
  - CartridgeAtropine
  - CartridgeSaline
  - SecHypo

- type: latheRecipePack
  id: SecurityWeaponsStaticGoob
  recipes:
  - PolymerBaton
  - SpearTelescopic

- type: latheRecipePack
  id: SecurityWeaponsNonEmaggableStaticGoob # At some point Terminus should be mapped and not printable, at least without research.
  recipes:
  - Terminus

## Dynamic
- type: latheRecipePack
  id: SecurityWeaponsGoob
  recipes:
  - WeaponSubMachineSmart
  - WeaponEnergyRifle
  - WeaponEnergyIonRifle
  - WeaponLaserCellRevolver
  - WeaponLaserCellSMG
  - WeaponLaserCellSniper
  - ClothingBackpackLMGBattery

- type: latheRecipePack
  id: SecurityAmmoGoob
  recipes:
  - EnergyMagRifleOverchargeLethal
  - EnergyMagRifleIon
  - EnergyMagRifleDisabler
  - EnergyMagRifleLethal
  - MagazineSmart
  - MagazineBoxShotgunIncendiaryHighCaliber
  - MagazineBoxShotgunBeanbagHighCaliber
  - MagazineBoxShotgunUraniumHighCaliber
  - PowerCellIRRevolver
  - PowerCellIonRevolver
  - PowerCellXrayRevolver
  - PowerCellOverchargedRevolver
  - PowerCellIRSMG
  - PowerCellIonSMG
  - PowerCellXraySMG
  - PowerCellOverchargedSMG
  - PowerCellIRSniper
  - PowerCellIonSniper
  - PowerCellXraySniper
  - PowerCellOverchargedSniper
  - MilitaryPowerCellLMG

- type: latheRecipePack
  id: SecurityEquipmentDynamicGoob
  recipes:
  - HoloprojectorSecurityAdvanced

- type: latheRecipePack
  id: SecurityCybernetics
  parent: MedicalCybernetics
  recipes:
  - SecurityCyberneticEyes
