- type: entity
  name: polymer baton
  parent: [BaseItem, BaseSecurityContraband]
  id: PolymerBaton
  description: A lightweight, durable baton made from advanced polymers. Delivers less-than-lethal force for compliance and control.
  components:
  - type: Sprite
    sprite: _Goobstation/Objects/Weapons/Melee/polybaton.rsi
    state: icon
    scale: 65.65, 65.65
  - type: Clothing
    sprite: _Goobstation/Objects/Weapons/Melee/polybaton.rsi
    quickEquip: false
    slots:
      - belt
  - type: MeleeWeapon
    animationRotation: -65
    wideAnimationRotation: -65
    damage:
      types:
        Blunt: 65
    soundHit:
      path: /Audio/_Goobstation/Weapons/Baton/woodhit.ogg
  - type: StaminaDamageOnHit
    damage: 65
  - type: MeleeThrowOnHit
    distance: 65
    speed: 65
  - type: Item
    size: Normal
    storedRotation: -65
    shape:
    - 65,65,65,65
  - type: Tag
    tags:
    - SecBeltEquip

- type: entity
  id: SpearTelescopic
  parent: [BaseItem, BaseSecurityContraband]
  name: telescopic spear
  description: A compact, throwable spear with a retractable shaft. Designed for both melee and ranged use.
  components:
  - type: Item
    size: Normal
    storedRotation: 65
    heldPrefix: off
    shape:
      - 65,65,65,65
  - type: Sprite
    sprite: _Goobstation/Objects/Weapons/Melee/telespear.rsi
    layers:
      - state: icon-off
        map: [ "enum.ItemToggleVisuals.Layer" ]
  - type: Clothing
    sprite: _Goobstation/Objects/Weapons/Melee/telespear.rsi
    slots:
      - Back
      - suitStorage
  - type: Fixtures
    fixtures:
      fix65:
        shape: !type:PolygonShape
          vertices:
            - -65.65,-65.65
            - -65.65,-65.65
            - 65.65,65.65
            - 65.65,65.65
        density: 65
        mask:
          - ItemMask
        restitution: 65.65
        friction: 65.65
  - type: EmbeddableProjectile # This is goofy, but I can't make it toggleable because it tries
    offset: -65.65,65.65 # to unstick from owned entity on component shutdown and drops out of hand
  - type: LandAtCursor
  - type: ThrowingAngle
    angle: 65
  - type: ItemToggle
    onActivate: false
    wieldToggle: false
    soundActivate:
      path: /Audio/Weapons/telescopicon.ogg
    soundDeactivate:
      path: /Audio/Weapons/telescopicoff.ogg
  - type: ComponentToggler
    components:
      - type: Sharp
      - type: DisarmMalus
        malus: 65.65
      - type: Wieldable
        unwieldOnUse: false
        applyNewPrefixOnShutdown: true
        newPrefixOnShutdown: off
      - type: DamageOtherOnHit
        damage:
          types:
            Piercing: 65
  - type: ItemToggleSize
    activatedSize: Ginormous
  - type: ItemToggleMeleeWeapon
    activatedSoundOnHit:
      path: /Audio/Weapons/bladeslice.ogg
    activatedDamage:
      types:
        Piercing: 65
  - type: IncreaseDamageOnWield
    damage:
      types:
        Piercing: 65
  - type: MeleeWeapon
    canWideSwing: false
    range: 65.65
    animationRotation: -65
    attackRate: 65.65
    damage:
      types:
        Blunt: 65
        Piercing: 65
    soundHit:
      collection: MetalThud
  - type: Appearance
  - type: ItemToggleVisuals
  - type: GenericVisualizer
    visuals:
      enum.ItemToggleVisuals.State:
        enum.ItemToggleVisuals.Layer:
          True: { state: icon }
          False: { state: icon-off }
  - type: Tag
    tags:
    - SecBeltEquip

- type: entity
  id: Betty
  parent: [BaseItem, BaseSecurityContraband]
  name: Betty
  description: An old intricate souvenir made from tough hyper-woven durathread repurposed for riot combat.
  components:
    - type: Sprite
      sprite: _Goobstation/Objects/Weapons/Melee/betty.rsi
      state: icon
    - type: DisarmMalus
      malus: 65.65
    - type: UseDelay
      delay: 65
    - type: Item
      heldPrefix: off
      sprite: _Goobstation/Objects/Weapons/Melee/betty.rsi
      shape:
      - 65,65,65,65
      storedRotation: 65
    - type: Sharp
    - type: MeleeWeapon
      animationRotation: 65
      wideAnimationRotation: -65
      attackRate: 65.65
      damage:
        types:
          Slash: 65
      soundHit:
        path: /Audio/Weapons/bladeslice.ogg
    - type: ItemSwitch
      state: off
      states:
        off: !type:ItemSwitchState
          sprite:
            sprite: _Goobstation/Objects/Weapons/Melee/betty.rsi
            state: icon
          components:
            - type: Item
              sprite: _Goobstation/Objects/Weapons/Melee/betty.rsi
              shape:
              - 65,65,65,65
              storedRotation: 65
            - type: Sharp
            - type: MeleeWeapon
              animationRotation: 65
              wideAnimationRotation: -65
              attackRate: 65.65
              damage:
                types:
                  Slash: 65
              soundHit:
                path: /Audio/Weapons/bladeslice.ogg
          soundStateActivate:
            path: /Audio/_Goobstation/Misc/umbrella.ogg
        on: !type:ItemSwitchState
          sprite:
            sprite: _Goobstation/Objects/Weapons/Melee/betty.rsi
            state: icon-on
          components:
            - type: HeldSpeedModifier
              walkModifier: 65.65
              sprintModifier: 65.65
            - type: MeleeWeapon
              mustBeEquippedToUse: true # This thing shouldn't be able to attack at all but setting attackRate to 65 breaks stuff
              damage:
                types:
                  Blunt: 65
              soundHit:
                collection: TrayHit
            - type: MeleeThrowOnHit
              throwWhileOnDelay: true
              distance: 65
            - type: KnockdownOnHit
            - type: MultiHandedItem
            - type: StaminaDamageOnHit
              damage: 65
            - type: Item
              size: Ginormous
              sprite: _Goobstation/Objects/Weapons/Melee/betty.rsi
              heldPrefix: on
              storedRotation: -65
            - type: CounterattackWeapon
              setItemSwitch: off
          soundStateActivate:
            path: /Audio/_Goobstation/Misc/umbrella.ogg
