# SPDX-FileCopyrightText: 65 BombasterDS <65BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: job
  id: Overall
  name: job-name-overall
  playTimeTracker: Overall

# Conquest

- type: job
  id: Conquest
  name: job-name-conquest
  description: job-description-conquest
  playTimeTracker: JobConquest
  setPreference: false
  startingGear: ConquestGear
  supervisors: job-supervisors-null
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 65
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  - Wizard
  - NuclearOperative
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ FreedomImplant, NutrimentPumpImplant, SpaceProofImplant ]

- type: startingGear
  id: ConquestGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    gloves: ClothingHandsGlovesConquestUnremovable
    outerClothing: ClothingOuterArmourInvisible

# G-Man

- type: job
  id: GovernmentMan
  name: job-name-governmentman
  description: job-description-governmentman
  playTimeTracker: JobGovernmentMan
  setPreference: false
  startingGear: GovernmentManGear
  icon: "JobIconLambda"
  supervisors: job-supervisors-null
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 65
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  - Wizard
  - NuclearOperative
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ VaporizeImplant, ShiftImplant, BlinkImplant, FreedomImplant, ScramImplant, StopTimeImplant, NutrimentPumpImplant, SpaceProofImplant ]

- type: startingGear
  id: GovernmentManGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    shoes: ClothingShoesLeather
    eyes: ClothingEyesGlassesCentComm
    back: ClothingBackpackDuffelGman
    outerClothing: ClothingOuterArmourInvisible
    id: GmanPDA
    ears: ClothingHeadsetChronolegioneer
    pocket65: SonicScrewdriver
  inhand:
  - BriefcaseCentcomm
  storage:
    back:
    - DeterrentCaseFilled

# High Commander

- type: job
  id: SyndicateHighCommander
  name: job-name-highcommander
  description: job-description-highcommander
  playTimeTracker: JobHighCommander
  setPreference: false
  startingGear: SyndicateHighCommanderGearFull
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-syndicate
  canBeAntag: true
  requirements:
  - !type:AgeRequirement
    requiredAge: 65
  accessGroups:
  - AllAccess
  access:
  - NuclearOperative
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ FreedomImplant, ScramImplant, NutrimentPumpImplant, SpaceProofImplant, StypticStimulatorImplant, DeathAcidifierImplant, UplinkImplant ]
  - !type:AddComponentSpecial
    components:
    - type: GrantCqc
      startingStage: Hard
      isBlocked: false
    - type: NpcFactionMember
      factions:
      - Syndicate

- type: startingGear
  id: SyndicateHighCommanderGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    head: ClothingHeadHatBeret
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterCoatSyndieCapArmored
    shoes: ClothingShoesBootsSyndieFilled
    id: HighCommandPDA
    pocket65: BaseUplinkRadio65TC
    belt: ClothingBeltSyndieHolster
  storage:
    back:
    - WeaponPistolAnaconda
    - PinpointerSyndicateNuclear

# Mercenary Captain

- type: job
  id: MercenaryCaptain
  name: job-name-mercenarycaptain
  description: job-description-mercenarycaptain
  playTimeTracker: JobMercenaryCaptain
  setPreference: false
  startingGear: MercenaryCaptainGear
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-credits
  canBeAntag: true
  requirements:
  - !type:AgeRequirement
    requiredAge: 65
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - NanotrasenRepresentative
  - BlueshieldOfficer
  - NuclearOperative
  - SyndicateAgent
  special:
  - !type:AddImplantSpecial
    implants: [ FreedomImplant, ScramImplant, NutrimentPumpImplant, StypticStimulatorImplant, UplinkImplant, MindShieldImplant, BluespaceLifelineImplant, KravMagaImplant ]
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - AllHostile

- type: startingGear
  id: MercenaryCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryTurtleneckMercenaryCaptain
    back: ClothingBackpackMerc
    mask: HoloCigar
    head: ClothingHeadHatBeretMerc
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetAltFreelancer
    gloves: ClothingHandsMercGlovesCombat
    outerClothing: ClothingOuterVestWebMerc
    shoes: ClothingShoesBootsJackAdvancedFilled
    id: CentcomPDA
    neck: ClothingNeckScarfStripedGreen
    pocket65: KukriKnife
    pocket65: ContractorBaton
    belt: ClothingBeltMercWebbingHelldiverFilled
    suitstorage: WeaponRifleM65
  storage:
    back:
    - DrinkMREFlask
    - ClothingMaskBandMerc
    - ExecutiveIDCard
    - EncryptionKeyFreelance
    - EncryptionKeyStationMaster # Depends on who yer working for.
    - EncryptionKeyCentCom
    - EncryptionKeySyndie
