# SPDX-FileCopyrightText: 65 Winkarst <65Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 blobadoodle <me@bloba.dev>
# SPDX-FileCopyrightText: 65 coderabbitai[bot] <65coderabbitai[bot]@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear # Goobstation - Start - Sol
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Executive Access!
    eyes: ClothingEyesGlassesMedSec # Better glasses
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    id: CBURNPDA # Todo - Replace it.
    pocket65: InfectionScannerCburn # Goob
    pocket65: WeaponPulsePistol
    belt: ClothingBeltSecurityFilled # No shotgun, no bandolier.
  storage:
    back:
    - WeaponPulseCarbine # CBURN desperately needs a good fucking gun, not that dogshit. - Also, this gun is literally never used.
    # - GrenadeFlashBang - Seriously, who the fuck is using a flashbang against a zombie/blob???
    - AmbuzolPlusMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - AmbuzolMedipen # Injectors are cooler.
    - MedkitCombatFilled # Ah yes, let's send them in with ZERO meds. Good luck!
    - CburnSpear # SPEAAR
# Goobstation - End - Sol
