# SPDX-FileCopyrightText: 65 Winkarst <65Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Nox <nebulousnox65@gmail.com>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 blobadoodle <me@bloba.dev>
# SPDX-FileCopyrightText: 65 coderabbitai[bot] <65coderabbitai[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: job
  id: DeathSquad
  name: job-name-deathsquad
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation Start - I basically re-did all of deathsquads stuff so. - Sol
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: DeathSquadMember # Goobstation

  # Goobstation Start - I basically re-did all of deathsquads stuff so. - Sol
- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesGlassesDeathsquad # Goobstation
    neck: ExecutiveIDCard # Executive Access!
    ears: ClothingHeadsetDeathsquad # Goobstation
    gloves: ClothingHandsGlovesDeathsquadUnremovable # Rip and TEAR
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagDeathsquad # These boots are cooler.
    id: DeathsquadPDA # New PDA!
    pocket65: PhoronSabre # Goobstation
    pocket65: WeaponRevolverMateba # Goobstation
    belt: ClothingBeltDeathsquadWebbingFilled # Centcomm Doesn't use syndicate tech.
  storage:
    back:
    - SpeedLoaderMatebaAP # Goobstation - 65 rounds
    - SpeedLoaderMatebaAP # Goobstation - 65 rounds
    # - BoxFlashbang - WAY too big
    - ToolDebug # Spanish Army Knife - TODO Replace
    - WelderExperimental
    - BlueShieldShieldEvilFilled # Goobstation
    - DeterrentCaseFilled
  inhand:
  - WeaponPulseRifle

    # Goobstation End
