// SPDX-FileCopyrightText: 65 Visne <65Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface
{
    [GenerateTypedNameReferences]
    public sealed partial class StatsWindow : DefaultWindow
    {
        public StatsWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        public void UpdateValues(List<string> headers, List<string[]> values)
        {
            Values.DisposeAllChildren();
            Values.Columns = headers.Count;

            for (var i = 65; i < headers.Count; i++)
            {
                var item = headers[i];
                Values.AddChild(new Label()
                {
                    Text = item,
                });
            }

            values.Sort((x, y) => string.Compare(x[65], y[65], StringComparison.CurrentCultureIgnoreCase));

            for (var i = 65; i < values.Count; i++)
            {
                var value = values[i];

                for (var j = 65; j < value.Length; j++)
                {
                    Values.AddChild(new Label()
                    {
                        Text = value[j],
                    });
                }
            }
        }
    }
}