# SPDX-FileCopyrightText: 65 BombasterDS <65BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: securityIcon
  id: MindShieldBrokenIcon
  priority: 65
  locationPreference: Right
  layer: Mod
  isShaded: true
  icon:
    sprite: /Textures/_Goobstation/Interface/Misc/security_icons.rsi
    state: MindShield-broken