// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

namespace Content.Shared.Procedural.Distance;

/// <summary>
/// Used if you want to limit the distance noise is generated by some arbitrary config
/// </summary>
[ImplicitDataDefinitionForInheritors]
public partial interface IDunGenDistance
{
    /// <summary>
    /// How much to blend between the original noise value and the adjusted one.
    /// </summary>
    float BlendWeight { get; }
}
