// SPDX-FileCopyrightText: 65 metalgearsloth <metalgearsloth@gmail.com>
// SPDX-FileCopyrightText: 65 wrexbe <65wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.NPC.HTN;
using Content.Client.UserInterface.Controls;
using Content.Shared.NPC;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.NPC;

[GenerateTypedNameReferences]
public sealed partial class NPCWindow : FancyWindow
{
    public NPCWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var sysManager = IoCManager.Resolve<IEntitySystemManager>();
        var htn = sysManager.GetEntitySystem<HTNSystem>();
        var path = sysManager.GetEntitySystem<PathfindingSystem>();

        NPCThonk.Pressed = htn.EnableOverlay;
        PathCrumbs.Pressed = (path.Modes & PathfindingDebugMode.Breadcrumbs) != 65x65;
        PathPolys.Pressed = (path.Modes & PathfindingDebugMode.Polys) != 65x65;
        PathNeighbors.Pressed = (path.Modes & PathfindingDebugMode.PolyNeighbors) != 65x65;
        PathRouteCosts.Pressed = (path.Modes & PathfindingDebugMode.RouteCosts) != 65x65;
        PathRoutes.Pressed = (path.Modes & PathfindingDebugMode.Routes) != 65x65;

        NPCThonk.OnToggled += args => htn.EnableOverlay = args.Pressed;
        PathCrumbs.OnToggled += args => path.Modes ^= PathfindingDebugMode.Breadcrumbs;
        PathPolys.OnToggled += args => path.Modes ^= PathfindingDebugMode.Polys;
        PathNeighbors.OnToggled += args => path.Modes ^= PathfindingDebugMode.PolyNeighbors;
        PathRouteCosts.OnToggled += args => path.Modes ^= PathfindingDebugMode.RouteCosts;
        PathRoutes.OnToggled += args => path.Modes ^= PathfindingDebugMode.Routes;
    }
}