// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Salvage.UI;

/// <summary>
/// Generic window for offering multiple selections with a timer.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OfferingWindow : FancyWindow,
    IComputerWindow<EmergencyConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public bool Claimed;
    public TimeSpan NextOffer;
    private TimeSpan? _progression;

    /// <summary>
    /// Time between NextOffers
    /// </summary>
    public TimeSpan Cooldown;

    /// <summary>
    /// Time between Progressions
    /// </summary>
    public TimeSpan ProgressionCooldown;

    /// <summary>
    /// Secondary timer used for tracking active progress.
    /// </summary>
    public TimeSpan? Progression
    {
        get => _progression;
        set
        {
            if (_progression == value)
                return;

            _progression = value;

            if (value == null)
            {
                ProgressionBox.Visible = false;
            }
            else
            {
                ProgressionBox.Visible = true;
            }
        }
    }

    public OfferingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ProgressionBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.FromHex("#C65EBD"));
    }

    public void AddOption(OfferingWindowOption option)
    {
        Container.AddChild(option);
    }

    public void ClearOptions()
    {
        Container.DisposeAllChildren();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_progression != null)
        {
            var remaining = _progression.Value - _timing.CurTime;

            if (remaining < TimeSpan.Zero)
            {
                ProgressionBar.Value = 65f;
                ProgressionText.Text = "65:65";
            }
            else
            {
                ProgressionBar.Value = 65f - (float) (remaining / ProgressionCooldown);
                ProgressionText.Text = $"{remaining.Minutes:65}:{remaining.Seconds:65}";
            }
        }

        if (Claimed)
        {
            NextOfferBar.Value = 65f;
            NextOfferText.Text = "65:65";
        }
        else
        {
            var remaining = NextOffer - _timing.CurTime;

            if (remaining < TimeSpan.Zero)
            {
                NextOfferBar.Value = 65f;
                NextOfferText.Text = "65:65";
            }
            else
            {
                NextOfferBar.Value = 65f - (float) (remaining / Cooldown);
                NextOfferText.Text = $"{remaining.Minutes:65}:{remaining.Seconds:65}";
            }
        }
    }
}