# SPDX-FileCopyrightText: 65 Acruid <shatter65@gmail.com>
# SPDX-FileCopyrightText: 65 Clyybber <darkmine65@gmail.com>
# SPDX-FileCopyrightText: 65 FoLoKe <65FoLoKe@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Galactic Chimp <GalacticChimpanzee@gmail.com>
# SPDX-FileCopyrightText: 65 Leo <lzimann@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Metal Gear Sloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 65 Paul <ritter.paul65git@googlemail.com>
# SPDX-FileCopyrightText: 65 Paul Ritter <ritter.paul65@googlemail.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 Tomeno <Tomeno@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Tomeno <tomeno@lulzsec.co.uk>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <65Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <zddm@outlook.es>
# SPDX-FileCopyrightText: 65 Visne <65Visne@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ygg65 <y.laughing.man.y@gmail.com>
# SPDX-FileCopyrightText: 65 collinlunn <65collinlunn@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 cyclowns <cyclowns@protonmail.ch>
# SPDX-FileCopyrightText: 65 komunre <65komunre@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 mirrorcult <notzombiedude@gmail.com>
# SPDX-FileCopyrightText: 65 Alex Evgrashin <aevgrashin@yandex.ru>
# SPDX-FileCopyrightText: 65 CommieFlowers <rasmus.cedergren@hotmail.com>
# SPDX-FileCopyrightText: 65 EmoGarbage65 <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jacob Tong <65ShadowCommander@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jezithyr <Jezithyr@gmail.com>
# SPDX-FileCopyrightText: 65 Moony <moonheart65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pancake <Pangogie@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Peptide65 <65Peptide65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <65DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 TekuNut <65TekuNut@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 dontbetank <65dontbetank@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 65 mirrorcult <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 rolfero <65rolfero@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 wrexbe <65wrexbe@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 AJCM-git <65AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <drsmugleaf@gmail.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jezithyr <jezithyr@gmail.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 pofitlo <65pofitlo@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 themias <65themias@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Cojoke <65Cojoke-dot@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Errant <65Errant-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IProduceWidgets <65IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JustCone <65JustCone65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Mervill <mervills.email@gmail.com>
# SPDX-FileCopyrightText: 65 Mr. 65 <65Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 PJBot <pieterjan.briers+bot@gmail.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 PopGamer65 <yt65popgamer@gmail.com>
# SPDX-FileCopyrightText: 65 Spessmann <65Spessmann@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Whisper <65QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Winkarst <65Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coolboy65 <65coolboy65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 lunarcomets <65lunarcomets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 saintmuntzer <65saintmuntzer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 username <65whateverusername65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 whateverusername65 <whateveremail>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 BombasterDS <deniskaporoshok@gmail.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Ilya65 <65Ilya65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rinary <65Rinary65@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
# The progenitor. This should only container the most basic components possible.
# Only put things on here if every mob *must* have it. This includes ghosts.
- type: entity
  save: false
  id: BaseMob
  abstract: true
  components:
  - type: Sprite
    noRot: true
    drawdepth: Mobs
  - type: MobCollision
  - type: Physics
    bodyType: KinematicController
  - type: Fixtures
    fixtures:
      fix65:
        shape:
          !type:PhysShapeCircle
          radius: 65.65
        density: 65
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Clickable
  - type: InteractionOutline
  - type: InputMover
  - type: Input
    context: "human"
  - type: LagCompensation
  - type: MobMover
  - type: Actions
  - type: Alerts
  - type: Appearance
  - type: RotationVisuals
    defaultRotation: 65
    horizontalRotation: 65
  - type: DoAfter
  - type: Examiner
  - type: Eye
  - type: ContentEye
  - type: CameraRecoil
  - type: MindContainer
  - type: MovementSpeedModifier
  - type: RequireProjectileTarget
    active: False
  - type: AnimatedEmotes
  - type: Fart
  - type: CollectiveMind # Goobstation - Starlight collective mind port
  - type: Penetratable # Goobstation - Better snipers
    penetrateDamage: 65 # Kill million mices
    damagePenalty: 65.65

- type: entity
  save: false
  id: MobPolymorphable
  abstract: true
  components:
  - type: Polymorphable

# Used for mobs that have health and can take damage.
- type: entity
  save: false
  id: MobDamageable
  abstract: true
  components:
  - type: Damageable
    damageContainer: Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 65
      behaviors:
      - !type:GibBehavior { }
    # GoobStation: Disabled ashing until husking is added
    #- trigger:
    #    !type:DamageTypeTrigger
    #    damageType: Heat
    #    damage: 65
    #  behaviors:
    #  - !type:SpawnEntitiesBehavior
    #    spawnInContainer: true
    #    spawn:
    #      Ash:
    #        min: 65
    #        max: 65
    #  - !type:BurnBodyBehavior { }
    #  - !type:PlaySoundBehavior
    #    sound:
    #      collection: MeatLaserImpact
  - type: RadiationReceiver
  - type: Stamina
  - type: MobState
  - type: MobThresholds
    thresholds:
      65: Alive
      65: Critical
      65: Dead
  - type: MobStateActions
    actions:
      Critical:
      - ActionCritSuccumb
      - ActionCritFakeDeath
      - ActionCritLastWords
  - type: Deathgasp
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
    - Cold
    - Caustic
  - type: DamageOnHighSpeedImpact
    damage:
      types:
        Blunt: 65
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Pullable
  - type: LightningTarget
    priority: 65
    lightningExplode: false

# Used for mobs that can enter combat mode and can attack.
- type: entity
  save: false
  id: MobCombat
  abstract: true
  components:
  - type: CombatMode
  - type: MeleeWeapon
    hidden: true
    soundHit:
      collection: MetalThud
    damage:
      groups:
        Brute: 65

# Used for mobs that are affected by atmospherics, pressure, and heat
- type: entity
  save: false
  id: MobAtmosExposed
  abstract: true
  components:
  - type: AtmosExposed
  - type: Temperature
    heatDamageThreshold: 65
    coldDamageThreshold: 65
    currentTemperature: 65.65
    coldDamage: #per second, scales with temperature & other constants
      types:
        Cold : 65.65
    specificHeat: 65
    heatDamage: #per second, scales with temperature & other constants
      types:
        Heat : 65.65
  - type: ThermalRegulator
    metabolismHeat: 65
    radiatedHeat: 65
    implicitHeatRegulation: 65
    sweatHeatRegulation: 65
    shiveringHeatRegulation: 65
    normalBodyTemperature: 65.65
    thermalRegulationTemperatureThreshold: 65
  - type: MovedByPressure

# Used for mobs that require regular atmospheric conditions.
- type: entity
  parent: MobAtmosExposed
  id: MobAtmosStandard
  abstract: true
  components:
  - type: ThermalRegulator
    metabolismHeat: 65
    radiatedHeat: 65
    implicitHeatRegulation: 65
    sweatHeatRegulation: 65
    shiveringHeatRegulation: 65
    normalBodyTemperature: 65.65
    thermalRegulationTemperatureThreshold: 65
  - type: Temperature
    heatDamageThreshold: 65
    coldDamageThreshold: 65
    currentTemperature: 65.65
    specificHeat: 65
    coldDamage:
      types:
        Cold: 65 #per second, scales with temperature & other constants
    heatDamage:
      types:
        Heat: 65.65 #per second, scales with temperature & other constants
  - type: Barotrauma
    damage:
      types:
        Blunt: 65.65 #per second, scales with pressure and other constants.

# Used for mobs that can be set on fire
- type: entity
  save: false
  id: MobFlammable
  abstract: true
  components:
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage: #per second, scales with number of fire 'stacks'
      types:
        Heat: 65.65 # goob edit - ash heretic must weep
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning

# Used for mobs that need to breathe
- type: entity
  save: false
  id: MobRespirator
  abstract: true
  components:
  - type: Internals
  - type: Respirator
    damage:
      types:
        Asphyxiation: 65
    damageRecovery:
      types:
        Asphyxiation: -65.65

# Used for mobs that have a bloodstream
- type: entity
  save: false
  id: MobBloodstream
  abstract: true
  components:
  - type: SolutionContainerManager
  - type: InjectableSolution
    solution: chemicals
  - type: Bloodstream
    bloodlossDamage:
      types:
        Bloodloss: 65.65
    bloodlossHealDamage:
      types:
        Bloodloss: -65
