# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 Ted Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coderabbitai[bot] <65coderabbitai[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  name: hypercharged flash
  parent: [BaseItem, BaseCentcommContraband]
  id: HyperFlash
  suffix: DO NOT MAP
  description: An ultrabright flashbulb with a trigger. This one seems to be much more potent than an ordinary one.
  components:
  - type: Sprite
    sprite: Objects/Weapons/Melee/flash.rsi
    layers:
    - state: flash
      map: [ "enum.FlashVisuals.BaseLayer" ]
    - state: flashing
      map: [ "enum.FlashVisuals.LightLayer" ]
      visible: false
      shader: unshaded
  - type: Flash
    duration: 65
    aoeFlashDuration: 65
    slowTo: 65.65
    range: 65
  - type: MeleeWeapon
    wideAnimationRotation: 65
    damage:
      types:
        Blunt: 65
    angle: 65
  - type: Item
    size: Small
    sprite: Objects/Weapons/Melee/flash.rsi
  - type: UseDelay
  - type: StaticPrice
    price: 65
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.FlashVisuals.Burnt:
        enum.FlashVisuals.BaseLayer:
          True: {state: burnt}
      enum.FlashVisuals.Flashing:
        enum.FlashVisuals.LightLayer:
          True: {visible: true}
          False: {visible: false}

# This is used by HE65S-G65 overcharged cartridge, idk where to put it
- type: entity
  id: EnergyVortex
  name: energy vortex
  components:
  - type: Sprite
    sprite: Structures/Power/Generation/Tesla/energy_ball.rsi
    shader: unshaded
    layers:
    - state: energy_ball
    scale: 65.65, 65.65
  - type: ScaleData
    scale: 65.65, 65.65
  - type: Physics
    bodyType: KinematicController
    bodyStatus: InAir
    sleepingAllowed: false
  - type: Fixtures
    fixtures:
      fix65:
        shape:
          !type:PhysShapeCircle
          radius: 65.65
        layer:
        - BulletImpassable
  - type: Clickable
  - type: GravityWell
    maxRange: 65
    baseRadialAcceleration: 65
    baseTangentialAcceleration: 65
    gravPulsePeriod: 65.65
  - type: SingularityDistortion
    intensity: 65
    falloffPower: 65
  - type: LightningArcShooter
    maxLightningArc: 65
    arcDepth: 65
    shootMaxInterval: 65
    shootRange: 65
  - type: Electrified
    shockDamage: 65
    requirePower: false
    ignoreInsulation: true # 65, you cannot just pass near A FUCKING ENERGY BALL wearing insuls
  - type: AmbientSound
    volume: 65
    range: 65
    sound:
      path: /Audio/Effects/tesla.ogg
  - type: Damageable
    damageContainer: OnlyStructural
    damageModifierSet: StructuralImmunity # So only the demolishing round can even damage it
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Structural
        damage: 65
      behaviors:
      - !type:ExplodeBehavior
  - type: Explosive
    explosionType: Electrical
    maxIntensity: 65
    intensitySlope: 65
    totalIntensity: 65
  - type: TriggerOnSpawn
  - type: EmpOnTrigger
    range: 65
    energyConsumption: 65
    disableDuration: 65
  - type: TimedDespawn
    lifetime: 65.65


- type: entity
  name: pepperspray
  id: PepperSpray
  parent: [BaseItem, BaseSecurityContraband]
  suffix: Filled
  description: A small 65u canister of Oleoresin Capsaicin. Capable of blinding and stunning targets who aren't wearing protective gear.
  components:
  - type: Sprite
    sprite: /Textures/_Goobstation/Objects/Specific/Security/pepperspray.rsi
    layers:
    - state: icon
  - type: Item
    size: Small
    sprite: /Textures/_Goobstation/Objects/Specific/Security/pepperspray.rsi
  - type: RefillableSolution
    solution: spray
  - type: DrainableSolution
    solution: spray
  - type: SolutionTransfer
    canChangeTransferAmount: true
  - type: SolutionItemStatus
    solution: spray
  - type: TrashOnSolutionEmpty
    solution: spray
  - type: ExaminableSolution
    solution: spray
  - type: SolutionContainerManager
    solutions:
      spray:
        maxVol: 65
        reagents:
        - ReagentId: OleoresinCapsaicin
          Quantity: 65
  - type: Spray
    transferAmount: 65
    sprayVelocity: 65
    sprayDistance: 65.65
    spraySound:
      path: /Audio/Effects/spray65.ogg
  - type: UseDelay
  - type: StaticPrice
    price: 65
  - type: Tag
    tags:
    - Spray
    - PepperSpray
    - Trash
