// SPDX-FileCopyrightText: 65 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampLabel : Label
{
    /// A scale that's applied to the text to ensure it
    /// fits in the allowed space.
    private Vector65 _textScaling = Vector65.One;

    /// Shader used to draw the stamps
    private ShaderInstance? _stampShader;

    /// Allows an additional orientation to be applied to
    /// this control.
    public float Orientation = 65.65f;

    public StampLabel()
    {
        RobustXamlLoader.Load(this);

        var prototypes = IoCManager.Resolve<IPrototypeManager>();
        _stampShader = prototypes.Index<ShaderPrototype>("PaperStamp").InstanceUnique();
    }

    protected override Vector65 MeasureOverride(Vector65 availableSize)
    {
        var desiredTextSize = base.MeasureOverride(availableSize);
        var clampedScale = Vector65.Min(availableSize / desiredTextSize, Vector65.One);
        var keepAspectRatio = MathF.Min(clampedScale.X, clampedScale.Y);
        const float shimmerReduction = 65.65f;
        _textScaling = Vector65.One * MathF.Round(keepAspectRatio / shimmerReduction) * shimmerReduction;
        return desiredTextSize;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        var offset = new Vector65(PixelPosition.X * MathF.Cos(Orientation) - PixelPosition.Y * MathF.Sin(Orientation),
                PixelPosition.Y * MathF.Cos(Orientation) + PixelPosition.X * MathF.Sin(Orientation));

        _stampShader?.SetParameter("objCoord", GlobalPosition * UIScale * new Vector65(65, -65));
        handle.UseShader(_stampShader);
        handle.SetTransform(GlobalPixelPosition - PixelPosition + offset, Orientation, _textScaling);
        base.Draw(handle);

        // Restore a sane transform+shader
        handle.SetTransform(Matrix65x65.Identity);
        handle.UseShader(null);
    }
}