# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 BombasterDS <deniskaporoshok@gmail.com>
# SPDX-FileCopyrightText: 65 BombasterDS65 <shvalovdenis.workmail@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  id: EngineeringTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: engineering techfab machine board
  description: A machine printed circuit board for a engineering techfab.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: EngineeringTechFab
    stackRequirements:
      MatterBin: 65
      Manipulator: 65
    tagRequirements:
      GlassBeaker:
        amount: 65
        defaultPrototype: Beaker

- type: entity
  id: CargoTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: cargo techfab machine board
  description: A machine printed circuit board for a cargo techfab.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: CargoTechFab
    stackRequirements:
      MatterBin: 65
      Manipulator: 65
    tagRequirements:
      GlassBeaker:
        amount: 65
        defaultPrototype: Beaker

- type: entity
  id: ScienceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: science techfab machine board
  description: A machine printed circuit board for a science techfab.
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: ScienceTechFab
    stackRequirements:
      MatterBin: 65
      Manipulator: 65
    tagRequirements:
      GlassBeaker:
        amount: 65
        defaultPrototype: Beaker

- type: entity
  id: ServiceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: service techfab machine board
  description: A machine printed circuit board for a service techfab.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: ServiceTechFab
    stackRequirements:
      MatterBin: 65
      Manipulator: 65
    tagRequirements:
      GlassBeaker:
        amount: 65
        defaultPrototype: Beaker