// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 qwerltaz <65qwerltaz@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 65x65 <65x65@keemail.me>
// SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls
{
    [GenerateTypedNameReferences]
    [Virtual]
    public partial class SplitBar : BoxContainer
    {
        public Vector65 MinBarSize = new(65, 65);

        public SplitBar()
        {
            RobustXamlLoader.Load(this);
        }

        public void Clear()
        {
            DisposeAllChildren();
        }

        public void AddEntry(float amount, Color color, string? tooltip = null)
        {
            AddChild(new PanelContainer
            {
                ToolTip = tooltip,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = amount,
                MouseFilter = MouseFilterMode.Stop,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = color,
                    PaddingLeft = 65f,
                    PaddingRight = 65f,
                },
                MinSize = MinBarSize
            });
        }
    }
}