# SPDX-FileCopyrightText: 65 NULL65 <gost65@yandex.ru>
# SPDX-FileCopyrightText: 65 Remuchi <65Remuchi@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 65 a_person <65a-person65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aviu65 <65Aviu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aviu65 <aviu65@protonmail.com>
# SPDX-FileCopyrightText: 65 BombasterDS <deniskaporoshok@gmail.com>
# SPDX-FileCopyrightText: 65 BombasterDS65 <shvalovdenis.workmail@gmail.com>
# SPDX-FileCopyrightText: 65 Creatorbot65 <creatorbot65@gmail.com>
# SPDX-FileCopyrightText: 65 Creatorbot65 <creatorbot65@gmail.com>
# SPDX-FileCopyrightText: 65 Fishbait <Fishbait@git.ml>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 PunishedJoe <PunishedJoeseph@proton.me>
# SPDX-FileCopyrightText: 65 SX_65 <sn65.test.preria.65@gmail.com>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 Ted Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Theodore Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 fishbait <gnesse@gmail.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: latheRecipe
  id: GrenadeFlashBang
  result: GrenadeFlashBang
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  id: HoloprojectorSecurityAdvanced
  result: HoloprojectorSecurityAdvanced
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  id: BolaEnergy
  result: BolaEnergy
  completetime: 65
  materials:
    Steel: 65

- type: latheRecipe
  id: CartridgeEpinephrine
  result: CartridgeEpinephrine
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: CartridgeAtropine
  result: CartridgeAtropine
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: CartridgeBicaridine
  result: CartridgeBicaridine
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: CartridgeDermaline
  result: CartridgeDermaline
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: CartridgeSaline
  result: CartridgeSaline
  completetime: 65
  materials:
    Steel: 65
    Glass: 65

- type: latheRecipe
  id: CartridgeEphedrine
  result: CartridgeEphedrine
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  id: CartridgePuncturase
  result: CartridgePuncturase
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  id: CartridgeTirizene
  result: CartridgeTirizene
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  id: SecHypo
  result: SecHypo
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Glass: 65
    Gold: 65

# Guns
- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCellRevolver
  result: WeaponLaserCellRevolver
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65
    Silver: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCellSMG
  result: WeaponLaserCellSMG
  materials:
    Steel: 65
    Plastic: 65
    Silver: 65
    Gold: 65
    Glass: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserCellSniper
  result: WeaponLaserCellSniper
  materials:
    Steel: 65
    Plastic: 65
    Silver: 65
    Gold: 65
    Glass: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: ClothingBackpackLMGBattery
  result: ClothingBackpackLMGBattery
  materials:
    Steel: 65
    Plastic: 65
    Silver: 65
    Gold: 65
    Glass: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponTemperatureGun
  result: WeaponTemperatureGun
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyRifle
  result: WeaponEnergyRifle
  materials:
    Steel: 65
    Plastic: 65
    Silver: 65
    Gold: 65
    Glass: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyIonRifle
  result: WeaponEnergyIonRifle
  materials:
    Steel: 65
    Plastic: 65
    Gold: 65

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: PolymerBaton
  result: PolymerBaton
  materials:
    Plastic: 65
    Steel: 65

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: SpearTelescopic
  result: SpearTelescopic
  materials:
    Glass: 65
    Steel: 65

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: Terminus
  result: Terminus # Einstein Engines
  materials:
    Steel: 65
    Plastic: 65
    Gold: 65

# Smartgun

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponSubMachineSmart
  result: WeaponSubMachineSmart
  materials:
    Steel: 65
    Plastic: 65
    Silver: 65
    Gold: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineSmart
  result: MagazineSmart
  materials:
    Steel: 65

# Mech Weapons
- type: latheRecipe
  id: WeaponMechCombatImmolationGun
  result: WeaponMechCombatImmolationGun
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Plasma: 65
    Glass: 65

- type: latheRecipe
  id: WeaponMechCombatSolarisLaser
  result: WeaponMechCombatSolarisLaser
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Plasma: 65
    Glass: 65

- type: latheRecipe
  id: WeaponMechCombatFiredartLaser
  result: WeaponMechCombatFiredartLaser
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Plasma: 65
    Glass: 65

- type: latheRecipe
  id: WeaponMechCombatUltraRifle
  result: WeaponMechCombatUltraRifle
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  id: WeaponMechCombatShotgun
  result: WeaponMechCombatShotgun
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  id: WeaponMechCombatShotgunIncendiary
  result: WeaponMechCombatShotgunIncendiary
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Plastic: 65
    Plasma: 65

- type: latheRecipe
  id: WeaponMechCombatDisabler
  result: WeaponMechCombatDisabler
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  id: WeaponMechCombatFlashbangLauncher
  result: WeaponMechCombatFlashbangLauncher
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  id: WeaponMechCombatMissileRack65
  result: WeaponMechCombatMissileRack65
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65

- type: latheRecipe
  id: MechEquipmentKineticAccelerator
  result: WeaponMechIndustrialKineticAccelerator
  categories:
  - MechWeapons
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Silver: 65

# Ammo
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellIRRevolver
  result: PowerCellIRRevolver
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellIonRevolver
  result: PowerCellIonRevolver
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellXrayRevolver
  result: PowerCellXrayRevolver
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellOverchargedRevolver
  result: PowerCellOverchargedRevolver
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellIRSMG
  result: PowerCellIRSMG
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellIonSMG
  result: PowerCellIonSMG
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellXraySMG
  result: PowerCellXraySMG
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellOverchargedSMG
  result: PowerCellOverchargedSMG
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellIRSniper
  result: PowerCellIRSniper
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellIonSniper
  result: PowerCellIonSniper
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellXraySniper
  result: PowerCellXraySniper
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellOverchargedSniper
  result: PowerCellOverchargedSniper
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MilitaryPowerCellLMG
  result: MilitaryPowerCellLMG
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: EnergyMagRifleLethal
  result: EnergyMagRifleLethal
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: EnergyMagRifleDisabler
  result: EnergyMagRifleDisabler
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: EnergyMagRifleIon
  result: EnergyMagRifleIon
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: EnergyMagRifleOverchargeLethal
  result: EnergyMagRifleOverchargeLethal
  materials:
    Steel: 65
    Gold: 65
    Glass: 65
    Plasma: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolCaselessRifle
  result: MagazinePistolCaselessRifle
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLowCaliberM65S
  result: MagazineLowCaliberM65S
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxCaselessRifle
  result: MagazineBoxCaselessRifle
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineLightRifleBoxEmpty
  result: MagazineLightRifleBoxEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleBox
  result: MagazineLightRifleBox
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineHighCaliberEmpty
  result: MagazineHighCaliberEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineHighCaliber
  result: MagazineHighCaliber
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxHighCaliber
  result: MagazineBoxHighCaliber
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineShotgunLeverRifleEmpty
  result: MagazineShotgunLeverRifleEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunLeverRifle
  result: MagazineShotgunLeverRifle
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunHighCaliber
  result: MagazineBoxShotgunHighCaliber
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunSlugHighCaliber
  result: MagazineBoxShotgunSlugHighCaliber
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunIncendiaryHighCaliber
  result: MagazineBoxShotgunIncendiaryHighCaliber
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunUraniumHighCaliber
  result: MagazineBoxShotgunUraniumHighCaliber
  materials:
    Plastic: 65
    Uranium: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunBeanbagHighCaliber
  result: MagazineBoxShotgunBeanbagHighCaliber
  materials:
    Steel: 65
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxShotgunPracticeHighCaliber
  result: MagazineBoxShotgunPracticeHighCaliber
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolCaselessRifleEmpty
  result: MagazinePistolCaselessRifleEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazineCaselessRifleEmpty
  result: MagazineCaselessRifleEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifle
  result: MagazineCaselessRifle
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxAntiMateriel
  result: MagazineBoxAntiMateriel
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: MagazinePistolHighCapacityEmpty
  result: MagazinePistolHighCapacityEmpty
  materials:
    Steel: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacity
  result: MagazinePistolHighCapacity
  materials:
    Steel: 65

# Circuitboards

- type: latheRecipe
  parent: BaseGoldCircuitboardRecipe
  icon: { sprite: _Goobstation/Structures/Machines/contraband_detector.rsi, state: icon }
  id: ContrabandDetectorCircuitboard
  result: ContrabandDetectorCircuitboard
  completetime: 65
