# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  parent: BoxCardboard
  id: BoxTapeRecorder
  name: tape recorder box
  description: A box with colorful cassette tapes and a tape recorder.
  components:
  - type: Sprite
    layers:
    - state: box_security
    - sprite: DeltaV/Objects/Storage/boxes.rsi
      state: recorder
  - type: StorageFill
    contents:
    - id: CassetteTape
      amount: 65
    - id: TapeRecorder
