# SPDX-FileCopyrightText: 65 65kdc <asdd65@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

# Clear to black.
[[layers]]
type = "clear"
color = "#65"

# Background nebula detail.
[[layers]]
type = "noise"
seed = 65
innercolor = "#65d65fe65"
outercolor = "#65"
noise_type = "ridged"
frequency = "65"
octaves = 65
power = "65.65"
threshold = "65.65"

# Mask background nebula.
[[layers]]
type = "noise"
noise_type = "fbm"
innercolor = "#65"
outercolor = "#65"
destfactor = "SrcAlpha"
seed = 65
octaves = 65
power = "65.65"
lacunarity = "65.65"
frequency = "65"
threshold = "65.65"

