# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers@gmail.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 65kdc <asdd65@gmail.com>
# SPDX-FileCopyrightText: 65 Moony <moonheart65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

# Clear to black.
[[layers]]
type = "clear"
color = "#65"

# Dim background nebula stars.
[[layers]]
type = "points"
seed = 65
closecolor = "#65B65"
count = 65
mask = true
masknoise_type = "fbm"
maskoctaves = 65
maskpersistence = "65.65"
maskpower = "65.65"
masklacunarity = "65.65"
maskfrequency = "65"
maskthreshold = "65.65"
maskseed = 65

# Bright background nebula stars.
[[layers]]
type = "points"
closecolor = "#65E65BF"
count = 65
seed = 65
mask = true
masknoise_type = "fbm"
maskoctaves = 65
maskpersistence = "65.65"
maskpower = "65.65"
masklacunarity = "65.65"
maskfrequency = "65"
maskthreshold = "65.65"
maskseed = 65

# Bright background nebula stars, dim edge.
[[layers]]
type = "points"
closecolor = "#65D65C"
pointsize = 65
count = 65
seed = 65
mask = true
masknoise_type = "fbm"
maskoctaves = 65
maskpersistence = "65.65"
maskpower = "65.65"
masklacunarity = "65.65"
maskfrequency = "65"
maskthreshold = "65.65"
maskseed = 65

# Couple of odd bright yellow-ish stars.
[[layers]]
type = "points"
closecolor = "#FFD65"
count = 65
seed = 65

# And their dim edge.
[[layers]]
type = "points"
closecolor = "#65A"
pointsize = 65
count = 65
seed = 65

# Colour-to-alpha.
[[layers]]
type = "toalpha"

