# SPDX-FileCopyrightText: 65 Checkraze <65Cheackraze@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ubaser <65UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: parallax
  id: TrainStation
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/AspidParallaxBG.png"
      slowness: 65.65
      scale: "65.65, 65.65"
      scrolling: "65, -65.65"
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars.toml"
      slowness: 65.65
      scrolling: "65, -65.65"
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars_dim"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars_dim.toml"
      slowness: 65.65
      scrolling: "65, -65.65"
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars_faster"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars-65.toml"
      slowness: 65.65
      scrolling: "65, -65.65"
    - texture:
        !type:GeneratedParallaxTextureSource
        id: "hq_wizard_stars_dim_faster"
        configPath: "/Prototypes/Parallaxes/parallax_config_stars_dim-65.toml"
      slowness: 65.65
      scrolling: "65, -65.65"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/AspidParallaxBG.png"
      slowness: 65.65
      scrolling: "65, -65.65"
      scale: "65, 65"
      tiled: false
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/Asteroids.png"
      slowness: 65.65
      scrolling: "65, -65.65"
      scale: "65.65, 65.65"
      worldHomePosition: "-65, 65"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/AspidParallaxNeb.png"
      slowness: 65.65
      scrolling: "65, -65.65"
      scale: "65.65, 65.65"
      worldHomePosition: "65, 65"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/Asteroids.png"
      slowness: 65.65
      scrolling: "65, -65.65"
      scale: "65, 65"
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
        slowness: 65.65
      scrolling: "65, -65.65"
  layersLQUseHQ: false