# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 starch <starchpersonal@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Armok <65ARMOKS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 LuciferMkshelter <65LuciferEOS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 Ted Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coderabbitai[bot] <65coderabbitai[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobNanotrasenRepresentative

- type: playTimeTracker
  id: JobHecuOperative

- type: playTimeTracker
  id: JobNavyOfficer

- type: playTimeTracker
  id: JobNavyCaptain

- type: playTimeTracker
  id: JobNavyOfficerUndercover

- type: playTimeTracker
  id: JobSpecialOperationsOfficer

- type: playTimeTracker
  id: JobDiplomat

- type: playTimeTracker
  id: JobInspector

- type: playTimeTracker
  id: JobNanotrasenCareerTrainer

- type: playTimeTracker
  id: JobHighCommander

- type: playTimeTracker
  id: JobGovernmentMan

- type: playTimeTracker
  id: JobConquest

- type: playTimeTracker
  id: JobMercenaryCaptain

- type: playTimeTracker
  id: JobBrigmedic
