# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  setPreference: false
  objective: roles-antag-subverted-silicon-objective