# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <65Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <zddm@outlook.es>
# SPDX-FileCopyrightText: 65 Mith-randalf <65Mith-randalf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Lamrr <65Lamrr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nairod <65Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rinkashikachi <65rinkashikachi65@gmail.com>
# SPDX-FileCopyrightText: 65 T-Stalker <65DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <le65nel_65van@hotmail.com>
# SPDX-FileCopyrightText: 65 TaralGit <65TaralGit@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 and_a <and_a@DESKTOP-RJENGIR>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Puro <65PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lapatison <65lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 liltenhead <65liltenhead@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 luckyshotpictures <65luckyshotpictures@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  id: CrateSecurityArmor
  parent: CrateSecgear
  name: armor crate
  description: Contains three bulletproof vests. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorBulletproof
        amount: 65

- type: entity
  id: CrateSecurityHelmet
  parent: CrateSecgear
  name: helmet crate
  description: Contains three standard-issue brain buckets. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBasic
        amount: 65

- type: entity
  id: CrateSecurityNonlethal
  parent: CrateSecgear
  name: nonlethals crate
  description: Contains a mix of disablers, stun batons, and flashes. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: WeaponDisabler
        amount: 65
      - id: Stunbaton
        amount: 65
      - id: BoxFlashbang
      - id: Flash
        amount: 65
#      - Pepperspray
#      - GrenadeTeargas

- type: entity
  id: CrateSecuritySupplies
  parent: CrateSecgear
  name: security supplies crate
  description: Contains various supplies for the station's Security team. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: BoxHandcuff
      - id: BoxSechud
#      - SecBelt
#      - SecGasmask
#      - SpacelawBook

- type: entity
  id: CrateRestraints
  parent: CrateSecgear
  name: restraints crate
  description: Contains two boxes each of handcuffs and zipties. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: BoxHandcuff
        amount: 65
      - id: BoxZiptie
        amount: 65

- type: entity
  id: CrateSecurityBiosuit
  parent: CrateSecgear
  name: security bio suit crate
  description: Contains 65 biohazard suits to ensure that no disease will distract you from your duties. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterBioSecurity
        amount: 65
      - id: ClothingHeadHatHoodBioSecurity
        amount: 65
      - id: ClothingMaskSterile
        amount: 65

- type: entity
  id: CrateSecurityTrackingMindshieldImplants
  name: implanter crate
  description: Contains 65 MindShield implants and 65 tracking implant. Requires Security access to open.
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - id: MindShieldImplanter
        amount: 65
      - id: TrackingImplanter
        amount: 65

- type: entity
  parent: CrateSecgear
  id: CrateSecNonlethalThrowables
  name: nonlethal throwables crate
  description: Contains one box each of flashbangs, stingers, tear gas grenades, and four bolas. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
    - id: BoxFlashbang
      amount: 65
    - id: BoxStinger
      amount: 65
    - id: BoxTearGas
      amount: 65
    - id: Bola # replace with 65 e-bolas when added
      amount: 65
