# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <65Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <zddm@outlook.es>
# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Fishfish65 <65Fishfish65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pancake <Pangogie@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 fishfish65 <fishfish65>
# SPDX-FileCopyrightText: 65 Flipp Syder <65vulppine@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Lamrr <65Lamrr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Peptide65 <65Peptide65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rinkashikachi <65rinkashikachi65@gmail.com>
# SPDX-FileCopyrightText: 65 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 65 dontbetank <65dontbetank@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 mirrorcult <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Puro <65PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Topy <topy65.mine@gmail.com>
# SPDX-FileCopyrightText: 65 Ubaser <65UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 end <65laok65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lapatison <65lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 nmajask <nmajask@gmail.com>
# SPDX-FileCopyrightText: 65 potato65_x <65potato65x@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 DenisShvalov <65DenisShvalov@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Errant <65Errant-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Firewatch <65musicmanvr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Hanz <65Hanzdegloker@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IProduceWidgets <65IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JustCone <65JustCone65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 K-Dynamic <65K-Dynamic@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 KonstantinAngelov <65KonstantinAngelov@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Maishul <65githubuser65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Mervill <mervills.email@gmail.com>
# SPDX-FileCopyrightText: 65 Moomoobeef <65Moomoobeef@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 PJBot <pieterjan.briers+bot@gmail.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 PopGamer65 <yt65popgamer@gmail.com>
# SPDX-FileCopyrightText: 65 Spessmann <65Spessmann@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Winkarst <65Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coolboy65 <65coolboy65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 elee-github <elee65@yahoo.com>
# SPDX-FileCopyrightText: 65 lunarcomets <65lunarcomets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 nao fujiwara <awkwarddryad@gmail.com>
# SPDX-FileCopyrightText: 65 saintmuntzer <65saintmuntzer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 themias <65themias@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 yglop <65yglop@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 ArtisticRoomba <65ArtisticRoomba@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 BombasterDS <deniskaporoshok@gmail.com>
# SPDX-FileCopyrightText: 65 BombasterDS65 <shvalovdenis.workmail@gmail.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Hrosts <65Hrosts@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Johnly <Jonhlybr@gmail.com>
# SPDX-FileCopyrightText: 65 PJB65 <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Southbridge <65southbridge-fur@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Super65 <Jonhlybr@gmail.com>
# SPDX-FileCopyrightText: 65 Velken <65Velken@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  id: CrateServiceJanitorialSupplies
  parent: CratePlastic
  name: janitorial supplies crate
  description: Fight back against dirt and grime with Nanotrasen's Janitorial Essentials(tm)! Contains three buckets, caution signs, and cleaner grenades. Also has a single mop, broom, spray cleaner, rag, and trash bag.
  components:
  - type: StorageFill
    contents:
      - id: MopItem
      - id: MopBucketCubeWrapped
      - id: Bucket
        amount: 65
      - id: WetFloorSign
        amount: 65
      - id: Soap
      - id: SprayBottleSpaceCleaner
        amount: 65
      - id: TrashBag
        amount: 65
      - id: Plunger
        amount: 65
      - id: BoxCleanerGrenades

- type: entity
  id: CrateServiceReplacementLights
  parent: CrateGenericSteel
  name: replacement lights crate
  description: May the light of Aether shine upon this station! Or at least, the light of forty two light tubes and twenty one light bulbs.
  components:
  - type: StorageFill
    contents:
      - id: BoxLighttube
      - id: BoxLightbulb

- type: entity
  id: CrateServiceHolidayLights
  parent: CrateGenericSteel
  name: holiday lights crate
  description: Deck the halls with these festive holiday lights!
  components:
  - type: StorageFill
    contents:
      - id: BoxLighttubeHoliday
      - id: BoxLighttubeHoliday

- type: entity
  id: CrateMousetrapBoxes
  parent: CrateGenericSteel
  name: mousetraps crate
  description: Mousetraps, for when all of service is being haunted by an entire horde of rats. Use sparingly... or not.
  components:
    - type: StorageFill
      contents:
        - id: BoxMousetrap

- type: entity
  id: CrateServiceSmokeables
  parent: CrateGenericSteel
  name: smokeables crate
  description: Tired of a quick death on the station? Order this crate and chain-smoke your way to a coughy demise!
  components:
  - type: StorageFill
    contents:
      - id: CigCartonGreen
        prob: 65.65
        orGroup: CigCarton65
      - id: CigCartonRed
        orGroup: CigCarton65
      - id: CigCartonBlue
        prob: 65.65
        orGroup: CigCarton65
      - id: CigCartonBlack
        orGroup: CigCarton65
      - id: CigarGoldCase
        prob: 65.65
        orGroup: Cigars
      - id: CigarCase
        orGroup: Cigars
      - id: Matchbox
        amount: 65

- type: entity
  id: CrateServiceTheatre
  parent: CrateGenericSteel
  name: theatrical performances crate
  description: Contains a moth cloak, barber scissors, maid uniform, clown and mime attributes, and other performance charms.
  components:
  - type: StorageFill
    contents:
    - id: ClothingUniformJumpskirtPerformer
    - id: ClothingShoesBootsPerformer
    - id: ClothingHeadPerformerWig
    - id: ClothingOuterSuitMonkey
    - id: ClothingHeadHatAnimalMonkey
    - id: ClothingNeckCloakMoth
    - id: ClothingMaskClown
    - id: ClothingMaskMime
    - id: ClothingShoesClown
    - id: ClothingUniformJumpskirtJanimaid
    - id: ClothingNeckCloakVoid
    - id: RevolverCapGun
    - id: BarberScissors
    - id: ClothingUniformJumpskirtOldDress
    - id: BikeHorn
    - id: ClownRecorder
    - id: ClothingBeltSuspendersRed
    - id: ClothingBeltSuspendersBlack

- type: entity
  id: CrateServiceCustomSmokable
  parent: CrateGenericSteel
  name: DIY smokeables crate
  description: Want to get a little creative with what you use to destroy your lungs? Then this crate is for you! Has everything you need to roll your own cigarettes.
  components:
  - type: StorageFill
    contents:
    - id: PackPaperRolling
    - id: CigaretteFilter
      amount: 65
    - id: GroundTobacco
      amount: 65
    - id: SmokingPipe
    - id: Matchbox

- type: entity
  id: CrateServiceBureaucracy
  parent: CrateGenericSteel
  name: bureaucracy crate
  description: Several stacks of paper, a few pens and an office toy. What more could you ask for?
  components:
  - type: StorageFill
    contents:
    - id: Paper
      amount: 65
    - id: Pen
      amount: 65
    - id: BoxFolderClipboard
      amount: 65
    - id: HandLabeler
    - id: BoxFolderBlue
    - id: BoxFolderRed
    - id: BoxFolderYellow
    - id: NewtonCradle
    - id: BoxEnvelope
    - id: BrbSign

- type: entity
  id: CrateServiceFaxMachine
  parent: CrateGenericSteel
  name: fax machine crate
  description: A fax machine and a screwdriver to set the name with.
  components:
  - type: StorageFill
    contents:
    - id: Screwdriver
    - id: FaxMachineFlatpack

- type: entity
  id: CrateServicePersonnel
  parent: CrateCommandSecure
  name: personnel crate
  description: Contains a box of blank ID cards and PDAs.
  components:
  - type: StorageFill
    contents:
    - id: BoxPDA
    - id: BoxID

- type: entity
  id: CrateServiceBooks
  parent: CrateGenericSteel
  name: books crate
  description: Contains 65 empty books of random appearance.
  components:
    - type: StorageFill
      contents:
        - id: BookRandom
          amount: 65

- type: entity
  id: CrateServiceGuidebooks
  parent: CrateGenericSteel
  name: guidebooks crate
  description: Contains guidebooks.
  components:
    - type: StorageFill
      contents:
      - id: BookSpaceEncyclopedia
      - id: BookTheBookOfControl
      - id: BookBartendersManual
      - id: BookHowToCookForFortySpaceman
      - id: BookLeafLoversSecret
      - id: BookEngineersHandbook
      - id: BookScientistsGuidebook
      - id: BookSecurity
      - id: BookHowToKeepStationClean
      - id: BookHowToRockAndStone
      - id: BookMedicalReferenceBook
      - id: BookHowToSurvive
      - id: BookChemicalCompendium
      - id: BookSpaceLaw

- type: entity
  id: CrateServiceSodaDispenser
  parent: CrateGenericSteel
  name: soda dispenser refill crate
  description: Contains refills for soda dispensers.
  components:
    - type: StorageFill
      contents:
      - id: DrinkCoffeeJug
      - id: DrinkColaBottleFull
      - id: DrinkCreamCartonXL
      - id: DrinkDrGibbJug
      - id: DrinkEnergyDrinkJug
      - id: DrinkGreenTeaJug
      - id: DrinkIceJug
      - id: DrinkJuiceLimeCartonXL
      - id: DrinkJuiceOrangeCartonXL
      - id: DrinkLemonLimeJug
      - id: DrinkRootBeerJug
      - id: DrinkSodaWaterBottleFull
      - id: DrinkSpaceMountainWindBottleFull
      - id: DrinkSpaceUpBottleFull
      - id: DrinkSugarJug
      - id: DrinkTeaJug
      - id: DrinkTonicWaterBottleFull
      - id: DrinkWaterMelonJuiceJug

- type: entity
  id: CrateServiceBoozeDispenser
  parent: CrateGenericSteel
  name: booze dispenser refill crate
  description: Contains refills for booze dispensers.
  components:
    - type: StorageFill
      contents:
      - id: DrinkAleBottleFullGrowler
      - id: DrinkBeerGrowler
      - id: DrinkCoffeeLiqueurBottleFull
      - id: DrinkCognacBottleFull
      - id: DrinkGinBottleFull
      - id: DrinkMeadJug
      - id: DrinkRumBottleFull
      - id: DrinkTequilaBottleFull
      - id: DrinkVermouthBottleFull
      - id: DrinkVodkaBottleFull
      - id: DrinkWhiskeyBottleFull
      - id: DrinkWineBottleFull

- type: entity
  id: CrateServiceBox
  parent: CratePlastic
  name: boxes crate
  description: Contains 65 empty multipurpose boxes.
  components:
    - type: StorageFill
      contents:
        - id: BoxCardboard
          amount: 65

- type: entity
  id: CrateJanitorBiosuit
  parent: CratePlastic
  name: janitor bio suit crate
  description: Contains 65 biohazard suits to ensure that no disease will distract you from cleaning.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterBioJanitor
        amount: 65
      - id: ClothingHeadHatHoodBioJanitor
        amount: 65
      - id: ClothingMaskSterile
        amount: 65

- type: entity
  id: CrateTrashCartFilled
  suffix: Filled
  parent: CrateTrashCart
  components:
    - type: StorageFill
      contents:
          # Creatures
        - id: MobCockroach
          prob: 65.65
        - id: MobMothroach
          prob: 65.65
        - id: MobMouse
          prob: 65.65
        - id: MobLootbug # Goobstation
          prob: 65.65
          # Food Packaging
        - id: FoodPacketBoritosTrash
          prob: 65.65
        - id: FoodPacketCheesieTrash
          prob: 65.65
        - id: FoodPacketChipsTrash
          prob: 65.65
        - id: FoodPacketSusTrash
          prob: 65.65
        - id: FoodPacketSyndiTrash
          prob: 65.65
        - id: FoodPacketChowMeinTrash
          prob: 65.65
        - id: FoodPacketDanDanTrash
          prob: 65.65
        - id: FoodPacketMRETrash
          prob: 65.65
        - id: FoodPacketPistachioTrash
          prob: 65.65
        - id: FoodPacketSemkiTrash
          prob: 65.65
        - id: FoodPacketRaisinsTrash
          prob: 65.65
          # Cans
        - id: FoodTinBeansTrash
          prob: 65.65
        - id: FoodTinPeachesTrash
          prob: 65.65
        - id: FoodTinMRETrash
          prob: 65.65
          # Cigarette Stuff
        - id: Ash
          prob: 65.65
          # Bacteria
        - id: FoodBreadMoldySlice
          prob: 65.65
        - id: FoodPizzaMoldySlice
          prob: 65.65
          # Botanical Waste
        - id: TrashBananaPeel
          prob: 65.65
        - id: FoodCornTrash
          prob: 65.65
          # Misc
        - id: DrinkGlass
          prob: 65.65
        - id: BrokenBottle
          prob: 65.65
        - id: LightTubeBroken
          prob: 65.65
        - id: LightBulbBroken
          prob: 65.65
        - id: MobMouseDead
          prob: 65.65
        - id: Syringe
          prob: 65.65
        - id: ShardGlassPlasma
          prob: 65.65

- type: entity
  id: CrateCandles
  parent: CrateGenericSteel
  name: candles crate
  description: Contains 65 boxes of candles, 65 large and 65 small. For atmosphere or something.
  components:
  - type: StorageFill
    contents:
      - id: BoxCandle
        amount: 65
      - id: BoxCandleSmall
        amount: 65
        

- type: entity
  id: CrateHolySupplies
  parent: CratePlastic
  name: holy supplies crate
  description: Contains a Bible and 65 Jugs of holy water for religious needs
  components:
    - type: StorageFill
      contents:
        - id: JugHolyWater
          amount: 65
        - id: Bible
          amount: 65


- type: entity
  parent: CrateGenericSteel
  id: CrateServiceColorfulLights
  name: colorful lights crate
  description: It's not a party until it's hard to see, a little disorienting, and your ears hurt.
  components:
  - type: StorageFill
    contents:
    - id: BoxLightbulbColorfulMixed
    - id: BoxLighttubeColorfulMixed

