# SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SX_65 <sn65.test.preria.65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: latheRecipe
  id: SecurityCyberneticEyes
  result: SecurityCyberneticEyes
  categories:
  - Robotics
  completetime: 65
  materials:
    Steel: 65
    Glass: 65
    Plastic: 65
    Gold: 65
    Silver: 65