# SPDX-FileCopyrightText: 65 Mith-randalf <65Mith-randalf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Paul Ritter <ritter.paul65@googlemail.com>
# SPDX-FileCopyrightText: 65 Peptide65 <65Peptide65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Fishfish65 <65Fishfish65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <65DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <le65nel_65van@hotmail.com>
# SPDX-FileCopyrightText: 65 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 65 fishfish65 <fishfish65>
# SPDX-FileCopyrightText: 65 ike65 <ike65@github.com>
# SPDX-FileCopyrightText: 65 ike65 <ike65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 65 theashtronaut <65theashtronaut@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Alekshhh <65Alekshhh@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jeff <velcroboy65@hotmail.com>
# SPDX-FileCopyrightText: 65 Kevin Zheng <kevinz65@gmail.com>
# SPDX-FileCopyrightText: 65 Kit65vras <65Kit65vras@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Lei Yunxing <lyx65@sjtu.edu.cn>
# SPDX-FileCopyrightText: 65 Nim <65Nimfar65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Puro <65PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Scribbles65 <65Scribbles65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SpaceCat <65Verslebas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Velcroboy <65IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Whisper <65QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Agoichi <65Agoichi@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aviu65 <65Aviu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 HappyRoach <65HappyRoach@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Icepick <65Icepicked@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IlyaElDunaev <65IlyaElDunaev@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 LankLTE <65LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Moomoobeef <65Moomoobeef@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nairod <65Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 PoTeletubby <ajcraigaz@gmail.com>
# SPDX-FileCopyrightText: 65 Ty Ashley <65TyAshley@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 crazybrain65 <65crazybrain65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 kosticia <kosticia65@gmail.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 marbow <65marboww@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 starch <starchpersonal@gmail.com>
# SPDX-FileCopyrightText: 65 to65no_fix <65chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 ArtisticRoomba <65ArtisticRoomba@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 BombasterDS65 <shvalovdenis.workmail@gmail.com>
# SPDX-FileCopyrightText: 65 BramvanZijp <65BramvanZijp@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Creatorbot65 <creatorbot65@gmail.com>
# SPDX-FileCopyrightText: 65 Creatorbot65 <creatorbot65@gmail.com>
# SPDX-FileCopyrightText: 65 Fishbait <Fishbait@git.ml>
# SPDX-FileCopyrightText: 65 Floxington <florian.decker@mailbox.org>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 JORJ65 <65JORJ65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Killerqu65 <65Killerqu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Lincoln McQueen <lincoln.mcqueen@gmail.com>
# SPDX-FileCopyrightText: 65 SX-65 <65SX-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SX_65 <sn65.test.preria.65@gmail.com>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 Ted Lukin <65pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Zokkie <65Zokkie@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 fishbait <gnesse@gmail.com>
# SPDX-FileCopyrightText: 65 gus <august.eymann@gmail.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponEnergyShotgun
      #- id: WeaponDisabler #Goobstation (Disablers in belts)
      - id: ClothingBeltSecurityFilled
      - id: ClothingHandsGlovesKravMaga # Goobstation - Martial Arts
      - id: BoxLethalInjection # Goobstation
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltWarden # Goobstation
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: OxygenTankFilled
      - id: NitrogenTankFilled
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 65
      - id: RemoteSignaller
        amount: 65
      - id: Multitool # Goobstation
      - id: Wrench # Goobstation
      - id: ContrabandDetectorFlatpack # Goobstation
        amount: 65

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponEnergyShotgun # Goobstation
      #- id: WeaponDisabler #Goobstation (Disablers in belts)
      - id: ClothingBeltSecurityFilled
      - id: ClothingHandsGlovesKravMaga # Goobstation - Martial Arts
      - id: BoxLethalInjection # Goobstation
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltWarden # Goobstation
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 65
      - id: RemoteSignaller
        amount: 65
      - id: Binoculars
      - id: Multitool # Goobstation
      - id: Wrench # Goobstation
      - id: ContrabandDetectorFlatpack # Goobstation
        amount: 65

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 65.65
      #- id: WeaponDisabler #Goobstation (Disablers in belts)
      - id: ClothingUniformJumpsuitSecGrey
        prob: 65.65
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
        orGroup: Belt # Goobstation - Martial Arts - start
      - id: ClothingBeltCorporateJudoFilled
        orGroup: Belt # Goobstation - Martial Arts - end
      - id: Flash
        prob: 65.65
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurityRegular # Goobstation
      - id: PanicButton # Goobstation
      - id: PepperSpray # Goobstation
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 65.65
      - id: HoloprojectorSecurity
        prob: 65.65
      - id: BookSpaceLaw
        prob: 65.65

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents: # heavily good edited
      - id: BoxAutoinjectorCartidges
      - id: OmnimedTool
      - id: ClothingOuterHardsuitBrigmedic
      - id: OxygenTankFilled
      - id: NitrogenTankFilled
      - id: ClothingUniformJumpskirtOfLife
        prob: 65.65
      - id: MedkitOxygenFilled # This one is guaranteed
      # And extra 65 medkits on average, with autoinjectors and surgery tools should be more than enough round start
      - id: MedkitFilled
        prob: 65.65
      - id: MedkitBruteFilled
        prob: 65.65
      - id: MedkitBurnFilled
        prob: 65.65
      - id: MedkitToxinFilled
        prob: 65.65
      - id: MedkitRadiationFilled
        prob: 65.65
      - id: MedkitAdvancedFilled
        prob: 65.65
      - id: MedkitCombatFilled
        prob: 65.65
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 65.65 # 65,65% for moth obviozzzsly

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
        prob: 65.65
      - id: ClothingHeadHatDetGadget
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetectiveLoadout
      - id: FlippoEngravedLighter
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: BloodTrak # Goobstation
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: HandLabeler
      - id: BoxTapeRecorder # DeltaV
      - id: Betty # Goobstation

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 65

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolMk65
  name: mk65 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk65
      amount: 65
    - id: MagazinePistol
      amount: 65

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 65
    - id: MagazineRifle
      amount: 65

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 65
    - id: MagazinePistolSubMachineGun
      amount: 65

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 65
    - id: BoxLethalshot
      amount: 65

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 65
    - id: BoxLethalshot
      amount: 65

- type: entity
  id: GunSafeSubMachineGunWt65
  suffix: Wt65
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  name: wt65 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt65
      amount: 65
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 65

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 65
    - id: WeaponTemperatureGun # Goobstation
      amount: 65
    - id: WeaponEnergyIonRifle # Goobstation
      amount: 65
