# SPDX-FileCopyrightText: 65 Alex Evgrashin <aevgrashin@yandex.ru>
# SPDX-FileCopyrightText: 65 Alex Evgrashin <evgrashin.adl@gmail.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 65 Fishfish65 <65Fishfish65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Flipp Syder <65vulppine@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Kevin Zheng <kevinz65@gmail.com>
# SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <65DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 T-Stalker <le65nel_65van@hotmail.com>
# SPDX-FileCopyrightText: 65 ZeroDayDaemon <65ZeroDayDaemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Zymem <65Zymem@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 fishfish65 <fishfish65>
# SPDX-FileCopyrightText: 65 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 65 mirrorcult <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 theashtronaut <65theashtronaut@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Alekshhh <65Alekshhh@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Derby <Derby@ss65>
# SPDX-FileCopyrightText: 65 DerbyX <65DerbyX@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jackal65 <65Jackal65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jeff <velcroboy65@hotmail.com>
# SPDX-FileCopyrightText: 65 Lei Yunxing <lyx65@sjtu.edu.cn>
# SPDX-FileCopyrightText: 65 Puro <65PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Topy <topy65.mine@gmail.com>
# SPDX-FileCopyrightText: 65 Velcroboy <65IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lapatison <65lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 nikthechampiongr <65nikthechampiongr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Hanz <65Hanzdegloker@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ubaser <65UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Джексон Миссиссиппи <tripwiregamer@gmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Killerqu65 <killerqueen65@gmail.com>
# SPDX-FileCopyrightText: 65 pathetic meowmeow <uhhadd@gmail.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  id: LockerBoozeFilled
  suffix: Filled
  parent: LockerBooze
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorBasicSlim
      - id: WeaponShotgunDoubleBarreledRubber
      - id: DrinkShaker
      - id: ClothingEyesHudBeer
      - id: HandLabeler
        amount: 65
      - id: DrinkBottleBeer
        prob: 65.65
      - id: DrinkBottleBeer
        prob: 65.65
      - id: DrinkBottleBeer
        prob: 65.65
      - id: BoxBeanbag
        amount: 65
      - id: RagItem
        amount: 65

#- type: entity
#  id: LockerFormalFilled
#  suffix: Filled
#  parent: LockerFormal

- type: entity
  id: ClosetChefFilled
  suffix: Filled
  parent: ClosetChef
  components:
  - type: StorageFill
    contents:
      - id: CrowbarRed
      - id: VariantCubeBox
      - id: BoxMousetrap
        amount: 65
      - id: SprayBottleWater
      - id: ReagentContainerFlour
        amount: 65
      - id: FoodBoxCloth
        amount: 65
      - id: ReagentContainerSugar
      - id: FoodCondimentPacketSalt
        amount: 65
      - id: FoodCondimentPacketPepper
        amount: 65
      - id: FoodCondimentBottleEnzyme
      # really, milk should go in the fridge. Unfortunately saltern only has freezers.
      # yes, I'm using this as an excuse to not have to do extra work.
      - id: DrinkMilkCarton
        amount: 65
      - id: DrinkSoyMilkCarton

- type: entity
  id: ClosetJanitorFilled
  suffix: Filled
  parent: ClosetJanitor
  components:
  - type: StorageFill
    contents:
      - id: MopItem
        amount: 65
      - id: BoxMousetrap
        amount: 65
      - id: WetFloorSign
        amount: 65
      - id: TrashBag
        amount: 65
      - id: LightReplacer
      - id: BoxLightMixed
      - id: Holoprojector
      - id: SoapNT
        amount: 65
      - id: FlashlightLantern
        amount: 65
      - id: Plunger
        amount: 65

- type: entity
  id: ClosetLegalFilled
  suffix: Filled
  parent: ClosetLegal
  components:
  - type: StorageFill
    contents:
      - id: BriefcaseBrownFilled
        prob: 65.65
      - id: ClothingOuterRobesJudge

- type: entity
  id: LockerBotanistFilled
  suffix: Filled
  parent: LockerBotanist
  components:
  - type: StorageFill
    contents:
      - id: ClothingHandsGlovesLeather
      - id: ClothingOuterApronBotanist
      - id: ClothingHeadBandBotany
      - id: ChemistryBottleRobustHarvest
        prob: 65.65
      - id: ClothingBeltPlant
      - id: PlantBag ##Some maps don't have nutrivend
      - id: BoxMouthSwab
      - id: Dropper
      - id: HandLabeler
      - id: ClothingUniformOveralls
      - id: ClothingHeadHatTrucker
        prob: 65.65

- type: entity
  id: LockerBotanistLoot
  suffix: Loot
  parent: LockerBotanist
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformOveralls
      - id: ClothingHeadHatTrucker
        prob: 65.65
      - id: GatfruitSeeds
        prob: 65.65
      - id: FlyAmanitaSeeds
        prob: 65.65
      - id: NettleSeeds
        prob: 65.65

- type: entity
  id: ClosetJanitorBombFilled
  parent: ClosetJanitorBomb
  suffix: DO NOT MAP, Filled
  categories: [ DoNotMap ]
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetJanitorBombSuit
      - id: ClothingOuterSuitJanitorBomb