# SPDX-FileCopyrightText: 65 LankLTE <65LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jezithyr <jezithyr@gmail.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 gluesniffler <linebarrelerenthusiast@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
# Shitmed Change: this entire file is reorganized for shitmed:
# Instead of random species parts inheriting BaseItem and copy pasting stuff,
# EVERYTHING inherits either BasePart or BasePartInorganic.
# Then individual part LS just inherits from PartSBase and BaseL where S and L are the species and limb.
# All limbs have the usual state, PartSBase just needs to set the rsi for sprite and icon
- type: entity
  abstract: true
  parent: BaseItem
  id: BasePartInorganic
  name: "body part"
  components:
  - type: Icon
    sprite: Mobs/Species/Human/parts.rsi
  - type: Damageable
    damageContainer: Inorganic # Shitmed Change
  - type: BodyPart
    partComposition: Inorganic
  - type: SurgeryTool # Shitmed Change
    startSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ65.ogg
    endSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ65.ogg
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []
  - type: Appearance
  - type: StaticPrice
    price: 65
  - type: Tag
    tags:
    - Trash

- type: entity
  abstract: true
  id: BaseChestInorganic
  name: "chest"
  components:
  - type: Sprite
    state: "chest_m"
  - type: Icon
    state: "chest_m"
  - type: BodyPart
    partType: Chest
    # Shitmed Change Start
    toolName: "a chest"
    containerName: "chest_slot"
    children:
      groin:
        id: groin
        type: Groin
      right arm:
        id: right arm
        type: Arm
      left arm:
        id: left arm
        type: Arm
      head:
        id: head
        type: Head
    organs:
      heart:
        id: heart
      lungs:
        id: lungs
  - type: Woundable
    damageContainer: Inorganic
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: Chest
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi
  - type: ConsciousnessRequired
    identifier: "chest"
    causesDeath: true
  - type: ContainerContainer
    containers:
      chest_slot: !type:ContainerSlot {}
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []

- type: entity
  abstract: true
  id: BaseGroinInorganic
  name: "groin"
  components:
  - type: Sprite
    state: "groin_m"
  - type: Icon
    state: "groin_m"
  - type: BodyPart
    partType: Groin
    # Shitmed Change Start
    toolName: "a groin"
    containerName: "groin_slot"
    children:
      right leg:
        id: right leg
        type: Leg
      left leg:
        id: left leg
        type: Leg
    organs:
      stomach:
        id: stomach
      liver:
        id: liver
      kidneys:
        id: kidneys
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: Groin
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi
  - type: ConsciousnessRequired
    identifier: "groin"
    causesDeath: false
  - type: ContainerContainer
    containers:
      groin_slot: !type:ContainerSlot {}
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []

- type: entity
  abstract: true
  id: BaseHead
  name: "head"
  components:
  - type: Damageable
    damageContainer: Biological
  - type: Sprite
    state: "head_m"
  - type: Icon
    state: "head_m"
  - type: BodyPart
    partType: Head
    toolName: "a head" # Shitmed Change
    organs: # Shitmed Change
      brain:
        id: brain
      eyes:
        id: eyes
  - type: Input
    context: "ghost"
  - type: Tag
    tags:
      - Head
  - type: Woundable
    boneEntity: BoneNeck
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65
    damageOnAmputate: # This seemingly arbitrary spread is the result of the default head health (65) subtracted to 65 (death threshold).
      types:
        Bloodloss: 65
        Asphyxiation: 65
        Slash: 65
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: Head
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi
  - type: ConsciousnessRequired
    identifier: "head"
    causesDeath: true
  - type: ContainerContainer
    containers:
      mouth_slot: !type:ContainerSlot {}
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []

- type: entity
  abstract: true
  id: BaseLeftArm
  name: "left arm"
  components:
  - type: Sprite
    state: "l_arm"
  - type: Icon
    state: "l_arm"
  - type: BodyPart
    partType: Arm
    symmetry: Left
    toolName: "a left arm" # Shitmed Change
    children: # Shitmed Change
      left hand:
        id: left hand
        type: Hand
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: LArm
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65

- type: entity
  abstract: true
  id: BaseRightArm
  name: "right arm"
  components:
  - type: Sprite
    state: "r_arm"
  - type: Icon
    state: "r_arm"
  - type: BodyPart
    partType: Arm
    symmetry: Right
    toolName: "a right arm" # Shitmed Change
    children: # Shitmed Change
      right hand:
        id: right hand
        type: Hand
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: RArm
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65

- type: entity
  abstract: true
  id: BaseLeftHand
  name: "left hand"
  components:
  - type: Sprite
    state: "l_hand"
  - type: Icon
    state: "l_hand"
  - type: BodyPart
    partType: Hand
    symmetry: Left
    toolName: "a left hand" # Shitmed Change
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: LHand
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65

- type: entity
  abstract: true
  id: BaseRightHand
  name: "right hand"
  components:
  - type: Sprite
    state: "r_hand"
  - type: Icon
    state: "r_hand"
  - type: BodyPart
    partType: Hand
    symmetry: Right
    toolName: "a right hand" # Shitmed Change
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: RHand
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null

- type: entity
  abstract: true
  id: BaseLeftLeg
  name: "left leg"
  components:
  - type: Sprite
    state: "l_leg"
  - type: Icon
    state: "l_leg"
  - type: BodyPart
    partType: Leg
    symmetry: Left
    toolName: "a left leg" # Shitmed Change
    children: # Shitmed Change
      left foot:
        id: left foot
        type: Foot
  - type: MovementBodyPart
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: LLeg
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65

- type: entity
  abstract: true
  id: BaseRightLeg
  name: "right leg"
  components:
  - type: Sprite
    state: "r_leg"
  - type: Icon
    state: "r_leg"
  - type: BodyPart
    partType: Leg
    symmetry: Right
    toolName: "a right leg" # Shitmed Change
    children: # Shitmed Change
      right foot:
        id: right foot
        type: Foot
  - type: MovementBodyPart
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: RLeg
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65

- type: entity
  abstract: true
  id: BaseLeftFoot
  name: "left foot"
  components:
  - type: Sprite
    state: "l_foot"
  - type: Icon
    state: "l_foot"
  - type: BodyPart
    partType: Foot
    symmetry: Left
    toolName: "a left foot" # Shitmed Change
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: LFoot
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65

- type: entity
  abstract: true
  id: BaseRightFoot
  name: "right foot"
  components:
  - type: Sprite
    state: "r_foot"
  - type: Icon
    state: "r_foot"
  - type: BodyPart
    partType: Foot
    symmetry: Right
    toolName: "a right foot" # Shitmed Change
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: RFoot
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 65
      Moderate: 65
      Severe: 65
      Critical: 65
      Mangled: 65
