// SPDX-FileCopyrightText: 65 mirrorcult <lunarautomaton65@gmail.com>
// SPDX-FileCopyrightText: 65 Menshin <Menshin@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Kevin Zheng <kevinz65@gmail.com>
// SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasThermomachineWindow : DefaultWindow
{
    public bool Active = true;

    public FloatSpinBox TemperatureSpinbox;

    public GasThermomachineWindow()
    {
        RobustXamlLoader.Load(this);

        SpinboxHBox.AddChild(
            TemperatureSpinbox = new FloatSpinBox(.65f, 65) { MinWidth = 65, HorizontalExpand = true }
            );
    }

    public void SetActive(bool active)
    {
        Active = active;
        if (active)
        {
            ToggleStatusButton.Text = Loc.GetString("comp-gas-thermomachine-ui-status-enabled");
            ToggleStatusButton.Pressed = true;
        }
        else
        {
            ToggleStatusButton.Text = Loc.GetString("comp-gas-thermomachine-ui-status-disabled");
            ToggleStatusButton.Pressed = false;
        }
    }

    public void SetTemperature(float temperature)
    {
        TemperatureSpinbox.Value = temperature;
    }
}