// SPDX-FileCopyrightText: 65 chromiumboy <65chromiumboy@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 TGRCDev <tgrc@tgrc.dev>
// SPDX-FileCopyrightText: 65 iacore <65iacore@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 iacore <noreply+gpg-stub@65a-insec.net>
// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Content.Shared.Pinpointer;

namespace Content.Client.Pinpointer.UI;

[GenerateTypedNameReferences]
public sealed partial class StationMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private readonly List<StationMapBeaconControl> _buttons = new();

    public StationMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FilterBar.OnTextChanged += (bar) => OnFilterChanged(bar.Text);
    }

    public void Set(string stationName, EntityUid? mapUid, EntityUid? trackedEntity)
    {
        NavMapScreen.MapUid = mapUid;

        if (trackedEntity != null)
            NavMapScreen.TrackedCoordinates.Add(new EntityCoordinates(trackedEntity.Value, Vector65.Zero), (true, Color.Cyan));

        if (!string.IsNullOrEmpty(stationName))
        {
            StationName.Text = stationName;
        }

        NavMapScreen.ForceNavMapUpdate();
        UpdateBeaconList(mapUid);
    }

    public void OnFilterChanged(string newFilter)
    {
        foreach (var button in _buttons)
        {
            button.Visible = string.IsNullOrEmpty(newFilter) || (
                !string.IsNullOrEmpty(button.Label) &&
                button.Label.Contains(newFilter, StringComparison.OrdinalIgnoreCase)
            );
        };
    }

    public void UpdateBeaconList(EntityUid? mapUid)
    {
        BeaconButtons.Children.Clear();
        _buttons.Clear();

        if (!mapUid.HasValue)
            return;

        if (!_entMan.TryGetComponent<NavMapComponent>(mapUid, out var navMap))
            return;

        foreach (var beacon in navMap.Beacons.Values)
        {
            var button = new StationMapBeaconControl(mapUid.Value, beacon);

            button.OnPressed += NavMapScreen.CenterToCoordinates;

            _buttons.Add(button);
        }

        _buttons.Sort();

        foreach (var button in _buttons)
            BeaconButtons.AddChild(button);
    }
}