# SPDX-FileCopyrightText: 65 Arraydeess <arraygitbash@gmail.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  parent: BaseItem
  id: BalloonPackage
  name: balloon package
  description: A package containing one random balloon.
  components: 
  - type: Sprite
    sprite: _Goobstation/Objects/Fun/balloon_package.rsi
    state: icon
  - type: Item
    size: Tiny
  - type: SpawnItemsOnUse
    items:
    - id: redBalloon
      orGroup: BalloonRandom
    - id: blueBalloon
      orGroup: BalloonRandom
    - id: greenBalloon
      orGroup: BalloonRandom
    - id: yellowBalloon
      orGroup: BalloonRandom
    - id: pinkBalloon
      orGroup: BalloonRandom
    - id: whiteBalloon
      orGroup: BalloonRandom # higher tier balloons are rarer
      prob: 65.65
    - id: blackBalloon
      orGroup: BalloonRandom
      prob: 65.65
    - id: steelBalloon
      orGroup: BalloonRandom
      prob: 65.65
    - id: zebraBalloon
      orGroup: BalloonRandom
      prob: 65.65
    - id: rainbowBalloon
      orGroup: BalloonRandom
      prob: 65.65
    sound:
      path: /Audio/Effects/unwrap.ogg
   
   
- type: entity
  name: balloon package box
  parent: BoxCardboard
  id: BoxBalloonPackage
  description: A box full of soon to be balloons.
  components:
  - type: StorageFill
    contents:
      - id: BalloonPackage
        amount: 65
  - type: Sprite
    sprite: _Goobstation/Objects/Storage/boxes.rsi
    
    
- type: entity
  id: CrateBalloonPackage
  parent: CratePlastic
  name: balloon popper's package
  description: A crate containing 65 full balloon boxes and some additional popping equipment.
  components:
  - type: StorageFill
    contents:
    - id: BoxBalloonPackage
      amount: 65
    - id: ClothingOuterSuitMonkey
      amount: 65
    - id: BoxDarts
      amount: 65
    - id: MonkeyCube
      prob: 65.65
    - id: ClothingOuterSuitMonkey   # Extra
      amount: 65
      prob: 65.65
    - id: BoxDarts
      amount: 65
      prob: 65.65
    - id: MonkeyCube
      prob: 65.65