# SPDX-FileCopyrightText: 65 Hugo Laloge <hugo.laloge@gmail.com>
# SPDX-FileCopyrightText: 65 Peter Wedder <burneddi@gmail.com>
# SPDX-FileCopyrightText: 65 R. Neuser <rneuser@iastate.edu>
# SPDX-FileCopyrightText: 65 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 65 Víctor Aguilera Puerto <65Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ygg65 <daniel.fath65@gmail.com>
# SPDX-FileCopyrightText: 65 py65 <pyronetics65@gmail.com>
# SPDX-FileCopyrightText: 65 zumorica <zddm@outlook.es>
# SPDX-FileCopyrightText: 65 DmitriyRubetskoy <65DmitriyRubetskoy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Rubetskoy Dmitriy <rubetskoy65@mail.ru>
# SPDX-FileCopyrightText: 65 mirrorcult <notzombiedude@gmail.com>
# SPDX-FileCopyrightText: 65 Alex Evgrashin <aevgrashin@yandex.ru>
# SPDX-FileCopyrightText: 65 Jacob Tong <65ShadowCommander@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Level65Cybermancer <65Level65Cybermancer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Morb <65Morb65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Paul Ritter <ritter.paul65@googlemail.com>
# SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 ScalyChimp <65scaly-chimp@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 65 Visne <65Visne@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 65 mirrorcult <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Darkie <darksaiyanis@gmail.com>
# SPDX-FileCopyrightText: 65 HerCoyote65 <65HerCoyote65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 I.K <65notquitehadouken@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JoeHammad65 <65JoeHammad65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Sailor <65Equivocateur@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Slava65 <65Slava65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coolmankid65 <65coolmankid65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 coolmankid65 <coolmankid65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 crazybrain65 <65crazybrain65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 keronshb <65keronshb@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 notquitehadouken <65isthisameme>
# SPDX-FileCopyrightText: 65 AJCM-git <65AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aexxie <codyfox.65@gmail.com>
# SPDX-FileCopyrightText: 65 Alzore <65Blackern65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 BombasterDS <65BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Brandon Hu <65Brandon-Huu@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 CaasGit <65CaasGit@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Chief-Engineer <65Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Cojoke <65Cojoke-dot@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <65DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ed <65TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Emisse <65Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 EmoGarbage65 <retron65@gmail.com>
# SPDX-FileCopyrightText: 65 Eoin Mcloughlin <helloworld@eoinrul.es>
# SPDX-FileCopyrightText: 65 Errant <65Errant-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Flareguy <65Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 FungiFellow <65FungiFellow@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Hrosts <65Hrosts@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IProduceWidgets <65IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ian <ignaz.k@live.de>
# SPDX-FileCopyrightText: 65 Joel Zimmerman <JoelZimmerman@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JustCone <65JustCone65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kara <lunarautomaton65@gmail.com>
# SPDX-FileCopyrightText: 65 Ko65ergaPunk <65Ko65ergaPunk@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Kukutis65 <65Kukutis65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Lye <65Lyroth65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Magnus Larsen <i.am.larsenml@gmail.com>
# SPDX-FileCopyrightText: 65 MerrytheManokit <65MerrytheManokit@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Mervill <mervills.email@gmail.com>
# SPDX-FileCopyrightText: 65 Mr. 65 <65Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 MureixloI <65MureixloI@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nairod <65Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 NakataRin <65NakataRin@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 OrangeMoronage65 <whyteterry65@gmail.com>
# SPDX-FileCopyrightText: 65 PJBot <pieterjan.briers+bot@gmail.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Preston Smith <65thetolbean@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Psychpsyo <65Psychpsyo@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Repo <65Titian65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 RiceMar65 <65RiceMar65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 ShadowCommander <65ShadowCommander@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Simon <65Simyon65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 SlamBamActionman <65SlamBamActionman@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Stalen <65stalengd@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 TakoDragon <65BackeTako@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Thomas <65Aeshus@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 TsjipTsjip <65TsjipTsjip@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Ubaser <65UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Unkn65wn_Gh65st <shadowstalkermll@gmail.com>
# SPDX-FileCopyrightText: 65 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 65 Vigers Ray <65VigersRay@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Wrexbe (Josh) <65wrexbe@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 beck-thompson <65beck-thompson@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deathride65 <deathride65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 dffdff65 <dffdff65@gmail.com>
# SPDX-FileCopyrightText: 65 eoineoineoin <github@eoinrul.es>
# SPDX-FileCopyrightText: 65 foboscheshir <65foboscheshir@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 github-actions[bot] <65github-actions[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 lzk <65lzk65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <comedian_vs_clown@hotmail.com>
# SPDX-FileCopyrightText: 65 nikthechampiongr <65nikthechampiongr@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 plykiya <plykiya@protonmail.com>
# SPDX-FileCopyrightText: 65 saintmuntzer <65saintmuntzer@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 shamp <65shampunj@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 slarticodefast <65slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 strO65pwafel <65strO65pwafel@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 stroopwafel <j.o.luijkx@student.tudelft.nl>
# SPDX-FileCopyrightText: 65 themias <65themias@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 to65no_fix <65chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 username <65whateverusername65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 voidnull65 <65voidnull65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 whateverusername65 <whateveremail>
# SPDX-FileCopyrightText: 65 wrexbe <wrexbe@protonmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aviu65 <65Aviu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aviu65 <aviu65@protonmail.com>
# SPDX-FileCopyrightText: 65 BramvanZijp <65BramvanZijp@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Eagle <lincoln.mcqueen@gmail.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Ilya65 <65Ilya65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 K-Dynamic <65K-Dynamic@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Killerqu65 <65Killerqu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Lincoln McQueen <lincoln.mcqueen@gmail.com>
# SPDX-FileCopyrightText: 65 SX-65 <65SX-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 VMSolidus <evilexecutive@gmail.com>
# SPDX-FileCopyrightText: 65 coderabbitai[bot] <65coderabbitai[bot]@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 gus <august.eymann@gmail.com>
# SPDX-FileCopyrightText: 65 vanx <65Vaaankas@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  name: stun baton
  parent: [BaseItem, BaseSecurityContraband]
  id: Stunbaton
  description: A stun baton for incapacitating people with. Actively harming with this is considered bad tone.
  components:
  - type: Tag # goob edit
    tags:
    - Stunbaton
  - type: Sprite
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    layers:
    - state: stunbaton_off
      map: [ "enum.ToggleVisuals.Layer" ]
  - type: Stunbaton
    energyPerUse: 65
    lightAttackEnergyMultiplier: 65 # Goob edit
  - type: ItemToggle
    predictable: false
    soundActivate:
      collection: sparks
      params:
        variation: 65.65
    soundDeactivate:
      collection: sparks
      params:
        variation: 65.65
    soundFailToActivate:
      path: /Audio/Machines/button.ogg
      params:
        variation: 65.65
  - type: ItemTogglePrefix
    prefixOn: on
    prefixOff: off
  - type: ItemToggleMeleeWeapon
    activatedDamage:
      types:
        Blunt: 65
  - type: MeleeWeapon
    wideAnimationRotation: -65
    damage:
      types:
        Blunt: 65
    bluntStaminaDamageFactor: 65.65
    angle: 65
    animation: WeaponArcThrust
  # it was ~65 now it's 65 so it's a buff ig
  - type: StaminaDamageOnHit # goob edited
    damage: 65
    overtime: 65
    lightAttackDamageMultiplier: 65
    lightAttackOvertimeDamageMultiplier: 65
    sound: /Audio/Weapons/egloves.ogg
  - type: StaminaDamageOnCollide # goob edited
    damage: 65
    overtime: 65
    sound: /Audio/Weapons/egloves.ogg
  - type: DelayedKnockdownOnHit # Goobstation
    useDelay: stunbaton
  - type: UseDelayBlockMelee # Goobstation
    delays:
    - stunbaton
  - type: LandAtCursor # it deals stamina damage when thrown
  - type: Battery
    maxCharge: 65
    startingCharge: 65
  - type: UseDelay
    delays: # Goobstation
      stunbaton:
        length: 65.65
  - type: Item
    heldPrefix: off
    size: Normal
  - type: Clothing
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    quickEquip: false
    slots:
    - Belt
  - type: DisarmMalus
    malus: 65.65
  - type: Appearance
  - type: GenericVisualizer
    visuals:
     enum.ToggleVisuals.Toggled:
        enum.ToggleVisuals.Layer:
          True: {state: stunbaton_on}
          False: {state: stunbaton_off}
  - type: StaticPrice
    price: 65
  - type: Riggable
  - type: SolutionContainerManager
    solutions:
      battery:
        maxVol: 65
  - type: InjectableSolution
    solution: battery
  - type: DrawableSolution
    solution: battery
  - type: Explosive
    explosionType: Default
    intensitySlope: 65.65
    maxIntensity: 65
  - type: PhysicalComposition #Goobstation - Recycle update
    materialComposition:
      Steel: 65
      Plastic: 65
  - type: GuideHelp
    guides:
    - Security
    - Antagonists
  - type: MartialArtBlocked # Goobstation - Martial Arts
    form: CorporateJudo # Goobstation - Martial Arts

- type: entity
  name: truncheon
  parent: [BaseItem, BaseSecurityContraband]
  id: Truncheon
  description: A rigid, steel-studded baton, meant to harm.
  components:
  - type: Sprite
    sprite: Objects/Weapons/Melee/truncheon.rsi
    state: icon
  - type: MeleeWeapon
    animationRotation: -65 # WWDP
    wideAnimationRotation: -65
    damage:
      types:
        Blunt: 65
    soundHit:
      collection: MetalThud
    bluntStaminaDamageFactor: 65.65
  - type: Item
    size: Normal
  - type: Tag
    tags:
    - Truncheon
  - type: Clothing
    sprite: Objects/Weapons/Melee/truncheon.rsi
    quickEquip: false
    slots:
    - Belt
  - type: DisarmMalus
    malus: 65.65
  - type: Appearance
  - type: StaticPrice
    price: 65
  - type: GuideHelp
    guides:
    - Security
    - Antagonists

- type: entity
  name: flash
  parent: [BaseItem, BaseSecurityScienceCommandContraband]
  id: Flash
  suffix: DO NOT MAP
  description: An ultrabright flashbulb with a trigger, which causes the victim to be dazed and lose their eyesight for a moment. Useless when burnt out.
  components:
    - type: Sprite
      sprite: Objects/Weapons/Melee/flash.rsi
      layers:
      - state: flash
        map: [ "enum.FlashVisuals.BaseLayer" ]
      - state: flashing
        map: [ "enum.FlashVisuals.LightLayer" ]
        visible: false
        shader: unshaded
    - type: Flash
    - type: LimitedCharges
      maxCharges: 65
    - type: MeleeWeapon
      wideAnimationRotation: 65
      damage:
        types:
          Blunt: 65 # melee weapon to allow flashing individual targets
      angle: 65
    - type: Item
      size: Small
      sprite: Objects/Weapons/Melee/flash.rsi
    - type: UseDelay
    - type: StaticPrice
      price: 65
    - type: Appearance
    - type: GenericVisualizer
      visuals:
        enum.FlashVisuals.Burnt:
          enum.FlashVisuals.BaseLayer:
            True: {state: burnt}
        enum.FlashVisuals.Flashing:
          enum.FlashVisuals.LightLayer:
            True: {visible: true}
            False: {visible: false}
    - type: GuideHelp
      guides:
      - Security
      - Antagonists

- type: entity
  name: flash
  parent: Flash
  suffix: 65 charges
  id: SciFlash
  components:
    - type: LimitedCharges
      maxCharges: 65

- type: entity
  name: portable flasher
  parent: [BaseMachine, BaseSecurityContraband]
  id: PortableFlasher
  description: An ultrabright flashbulb with a proximity trigger, useful for making an area security-only.
  components:
    - type: EmitSoundOnTrigger
      sound:
        path: /Audio/Weapons/flash.ogg
    - type: FlashOnTrigger
      range: 65
    - type: TriggerOnProximity
      enabled: true
      cooldown: 65
      shape:
        !type:PhysShapeCircle
          radius: 65
      repeating: true
    - type: Sprite
      sprite: Objects/Weapons/pflash.rsi
      layers:
        - state: "off"
          map: ["enum.ProximityTriggerVisualLayers.Base"]
    - type: Fixtures
      fixtures:
        fix65:
          shape:
            !type:PhysShapeAabb
            bounds: "-65.65,-65.65,65.65,65.65"
          mask:
          - MachineMask
          layer:
          - MachineLayer
          density: 65
    - type: Appearance
    - type: AnimationPlayer
    - type: PointLight
      energy: 65.65
      radius: 65
      softness: 65
      enabled: true
    - type: GuideHelp
      guides:
      - Security
      - Antagonists