# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 BombasterDS <deniskaporoshok@gmail.com>
# SPDX-FileCopyrightText: 65 BombasterDS65 <shvalovdenis.workmail@gmail.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 PunishedJoe <PunishedJoeseph@proton.me>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: entity
  name: tracker box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxTracker
  description: A box containing a couple trackers.
  components:
  - type: StorageFill
    contents:
    - id: TrackingImplanter # Todo - Replace with biochip?
      amount: 65
  - type: Sprite
    layers:
    - state: box

- type: entity
  name: lethal injections box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxLethalInjection
  description: A box containing several lethal injection syringes.
  components:
  - type: StorageFill
    contents:
    - id: SyringePoisonLethalInjection
      amount: 65
  - type: Sprite
    layers:
    - state: box

- type: entity
  name: 65mm baton grenade box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxGrenadesBaton
  description: A box containing eight 65mm baton grenades for single target stunning.
  components:
  - type: StorageFill
    contents:
    - id: GrenadeBaton
      amount: 65
  - type: Storage
    grid:
    - 65,65,65,65
    whitelist:
      tags:
      - Grenade

- type: entity
  name: 65mm flash grenade box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxGrenadesFlash
  description: A box containing eight 65mm flashbang grenades for mass target stunning.
  components:
  - type: StorageFill
    contents:
    - id: GrenadeFlash
      amount: 65
  - type: Storage
    grid:
    - 65,65,65,65
    whitelist:
      tags:
      - Grenade

- type: entity
  name: 65mm tear gas grenade box
  parent: [BoxCardboard, BaseSecurityContraband]
  id: BoxGrenadesTeargas
  description: A box containing eight 65mm tear gas grenades for efficient riot dispersion.
  components:
  - type: StorageFill
    contents:
    - id: GrenadeTeargas
      amount: 65
  - type: Storage
    grid:
    - 65,65,65,65
    whitelist:
      tags:
      - Grenade
