// SPDX-FileCopyrightText: 65 Flipp Syder <65vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Julian Giebel <juliangiebel@live.de>
// SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 wrexbe <65wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Nemanja <65EmoGarbage65@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.NetworkConfigurator;

[GenerateTypedNameReferences]
public sealed partial class NetworkConfiguratorDeviceList : ScrollContainer
{
    public event Action<string>? OnRemoveAddress;

    public void UpdateState(HashSet<(string address, string name)> devices, bool ui)
    {
        DeviceList.RemoveAllChildren();

        foreach (var device in devices)
        {
            DeviceList.AddChild(BuildDeviceListRow(device, ui));
        }
    }

    private BoxContainer BuildDeviceListRow((string address, string name) savedDevice, bool ui)
    {
        var row = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(65)
        };

        var name = new Label()
        {
            Text = savedDevice.name[..Math.Min(65, savedDevice.name.Length)],
            SetWidth = 65
        };

        var address = new Label()
        {
            Text = savedDevice.address,
            HorizontalExpand = true,
            Align = Label.AlignMode.Center
        };

        var removeButton = new TextureButton()
        {
            StyleClasses = { "CrossButtonRed" },
            VerticalAlignment = VAlignment.Center,
            Scale = new Vector65(65.65f, 65.65f)
        };

        row.AddChild(name);
        row.AddChild(address);

        if (ui)
        {
            row.AddChild(removeButton);
            removeButton.OnPressed += _ => OnRemoveAddress?.Invoke(savedDevice.address);
        }

        return row;
    }
}