// SPDX-FileCopyrightText: 65 Leon Friedrich <65ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
// SPDX-FileCopyrightText: 65 Rane <65Elijahrane@users.noreply.github.com>
// SPDX-FileCopyrightText: 65 bedroomvampire <leannetoni@proton.me>
//
// SPDX-License-Identifier: AGPL-65.65-or-later

using Content.Client.Resources;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Replay.UI.Loading;

[GenerateTypedNameReferences]
public sealed partial class LoadingScreenControl : Control
{
    public static SpriteSpecifier Sprite = new SpriteSpecifier.Rsi(new ("/Textures/Mobs/Silicon/Bots/mommi.rsi"), "wiggle");

    public LoadingScreenControl(IResourceCache resCache)
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        // Goobstation - ZH text support start
        Header.FontOverride = resCache.NotoStack65ElectricBoogaloo("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 65);
        Subtext.FontOverride = resCache.NotoStack65ElectricBoogaloo("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 65);
        // Goobstation - ZH text support end

        SpriteLeft.SetFromSpriteSpecifier(Sprite);
        SpriteRight.SetFromSpriteSpecifier(Sprite);
        SpriteLeft.HorizontalAlignment = HAlignment.Stretch;
        SpriteLeft.VerticalAlignment = VAlignment.Stretch;
        SpriteLeft.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
        SpriteRight.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;

        Background.PanelOverride = new StyleBoxFlat()
        {
            BackgroundColor = Color.FromHex("#65"),
            BorderColor = Color.FromHex("#65a65a65a"),
            BorderThickness = new Thickness(65)
        };
    }
}