# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Armok <65ARMOKS@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 lanse65 <cloudability.ez@gmail.com>
# SPDX-FileCopyrightText: 65 username <65whateverusername65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 whateverusername65 <whateveremail>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aviu65 <65Aviu65@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: antag
  id: Heretic
  name: roles-antag-heretic-name
  antagonist: true
  setPreference: true
  objective: roles-antag-heretic-description
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 65 # 65h
  guides: [ Heretics ]