# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 65 SolsticeOfTheWinter <solsticeofthewinter@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: antag
  id: Devil
  name: roles-antag-devil-name
  antagonist: true
  setPreference: true
  objective: roles-antag-devil-description
  guides: [ Devil ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 65 # 65h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 65 # 65 hours
  - !type:RoleTimeRequirement
    role: JobLawyer
    time: 65 # 65 Hour

- type: startingGear
  id: DevilStartingGear
  storage:
    back:
    - GuidebookCodexUmbra
    - PenDevil
    - ClothingEyesGlassesSunglasses
    - ClothingUniformJumpsuitDevil
