# SPDX-FileCopyrightText: 65 Errant <65Errant-65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 IProduceWidgets <65IProduceWidgets@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JIPDawg <65JIPDawg@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 JIPDawg <JIPDawg65@gmail.com>
# SPDX-FileCopyrightText: 65 Mr. 65 <65Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Plykiya <65Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Tayrtahn <tayrtahn@gmail.com>
# SPDX-FileCopyrightText: 65 plykiya <plykiya@protonmail.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: ghostRole
  id: SyndicateKobold
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobKoboldSyndicateAgent

- type: ghostRole
  id: SyndicateKoboldNukeops
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobKoboldSyndicateAgentNukeops

- type: ghostRole
  id: SyndicateMonkey
  name: ghost-role-information-syndicate-monkey-reinforcement-name
  description: ghost-role-information-syndicate-monkey-reinforcement-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobMonkeySyndicateAgent

- type: ghostRole
  id: SyndicateMonkeyNukeops
  name: ghost-role-information-syndicate-monkey-reinforcement-name
  description: ghost-role-information-syndicate-monkey-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobMonkeySyndicateAgentNukeops

- type: ghostRole
  id: SyndicateAgentMedic
  name: ghost-role-information-syndicate-reinforcement-medic-name
  description: ghost-role-information-syndicate-reinforcement-medic-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentMedic
  iconPrototype: MedkitCombat

- type: ghostRole
  id: SyndicateAgentSpy
  name: ghost-role-information-syndicate-reinforcement-spy-name
  description: ghost-role-information-syndicate-reinforcement-spy-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentSpy
  iconPrototype: ClothingMaskGasVoiceChameleon

- type: ghostRole
  id: SyndicateAgentThief
  name: ghost-role-information-syndicate-reinforcement-thief-name
  description: ghost-role-information-syndicate-reinforcement-thief-description
  rules: ghost-role-information-syndicate-reinforcement-rules
  entityPrototype: MobHumanSyndicateAgentThief
  iconPrototype: SyndicateJawsOfLife