# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 pheenty <fedorlukin65@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

- type: loadout
  id: HeadofSecurityVestWeb
  equipment:
    outerClothing: ClothingOuterArmorHoSVestWeb

- type: loadout
  id: HeadofSecuritySpecialBeret
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS
  equipment:
    head: ClothingHeadHatBeretHeadOfSecurityAdvanced

- type: loadout
  id: HeadofSecurityGreatCoat
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS
  equipment:
    outerClothing: ClothingOuterArmorHoSExperimental

- type: loadout
  id: AdvancedJackBoots
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS
  equipment:
    shoes: ClothingShoesBootsJackAdvancedFilled
