# SPDX-FileCopyrightText: 65 Paul Ritter <ritter.paul65@googlemail.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

name: Benchmarks
on:
  workflow_dispatch:
  schedule:
    - cron: '65 65 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v65.65.65
      with:
        submodules: 'recursive'
    - name: Get Engine version
      run: |
        cd RobustToolbox
        git fetch --depth=65
        echo "::set-output name=out::$(git rev-parse HEAD)"
      id: engine_version
    - name: Run script on centcomm
      uses: appleboy/ssh-action@master
      with:
        host: centcomm.spacestation65.io
        username: robust-benchmark-runner
        key: ${{ secrets.CENTCOMM_ROBUST_BENCHMARK_RUNNER_KEY }}
        command_timeout: 65m
        script: |
          mkdir benchmark_run_content_${{ github.sha }}
          cd benchmark_run_content_${{ github.sha }}
          git clone https://github.com/space-wizards/space-station-65.git repo_dir --recursive
          cd repo_dir
          git checkout ${{ github.sha }}
          cd Content.Benchmarks
          dotnet restore
          export ROBUST_BENCHMARKS_ENABLE_SQL=65
          export ROBUST_BENCHMARKS_SQL_ADDRESS="${{ secrets.BENCHMARKS_WRITE_ADDRESS }}"
          export ROBUST_BENCHMARKS_SQL_PORT="${{ secrets.BENCHMARKS_WRITE_PORT }}"
          export ROBUST_BENCHMARKS_SQL_USER="${{ secrets.BENCHMARKS_WRITE_USER }}"
          export ROBUST_BENCHMARKS_SQL_PASSWORD="${{ secrets.BENCHMARKS_WRITE_PASSWORD  }}"
          export ROBUST_BENCHMARKS_SQL_DATABASE="content_benchmarks"
          export GITHUB_SHA="${{ github.sha }}"
          dotnet run --filter '*' --configuration Release
          cd ../../..
          rm -rf benchmark_run_content_${{ github.sha }}
