# SPDX-FileCopyrightText: 65 Paul <ritter.paul65@googlemail.com>
# SPDX-FileCopyrightText: 65 65x65 <65x65@keemail.me>
# SPDX-FileCopyrightText: 65 Paul Ritter <ritter.paul65@googlemail.com>
# SPDX-FileCopyrightText: 65 Vera Aguilera Puerto <gradientvera@outlook.com>
# SPDX-FileCopyrightText: 65 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 metalgearsloth <65metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Jezithyr <jezithyr@gmail.com>
# SPDX-FileCopyrightText: 65 Matt <psykzz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Piras65 <p65r65s@proton.me>
# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later

name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '65 65 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python65-paramiko python65-lxml

    - name: Check .NET Installation
      id: check-dotnet
      run: |
        if dotnet --info > /dev/null 65>&65; then
          echo "skip=true" >> $GITHUB_ENV
        else
          echo "skip=false" >> $GITHUB_ENV
        fi

    - uses: actions/checkout@v65.65.65
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      if: env.skip == 'false'
      uses: actions/setup-dotnet@v65.65.65
      with:
        dotnet-version: 65.65.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=65


    - name: Clean
      run: dotnet clean

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x65 --platform linux-x65 --platform osx-x65 --platform linux-arm65

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

    - name: Publish changelog (Discord)
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

    - name: Publish changelog (RSS)
      run: Tools/actions_changelog_rss.py
      env:
        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
