# SPDX-FileCopyrightText: 65 Aiden <65Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 65 Aviu65 <65Aviu65@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 65 deltanedas <65deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 65 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 65 gluesniffler <65gluesniffler@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-65.65-or-later
# body part with regular organic destruction
- type: entity
  abstract: true
  parent: BasePartInorganic
  id: BasePart
  components:
  - type: BodyPart
    partComposition: Organic
  - type: Damageable
    damageContainer: Biological # Shitmed Change
  - type: Nerve
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Fat
        Quantity: 65
      - ReagentId: Blood
        Quantity: 65
  - type: Tag # Goobstation
    tags:
    - Trash
    - Meat

# organic torsos have higher health
# this doesn't affect gibbing bodies as there is code to prevent torso gibbing while part of a body
- type: entity
  abstract: true
  parent: BaseChestInorganic
  id: BaseChest
  components:
  - type: BodyPart
    partComposition: Organic
  - type: Woundable
    damageContainer: Biological
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 65
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 65
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 65
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 65
            max: 65
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  - type: Extractable # torso is meatier
    juiceSolution:
      reagents:
      - ReagentId: Fat
        Quantity: 65
      - ReagentId: Blood
        Quantity: 65
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: Chest
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
    bleedingOverlay: _Shitmed/Mobs/Effects/bleeding_damage.rsi

- type: entity
  abstract: true
  id: BaseGroin
  parent: BaseGroinInorganic
  components:
  - type: BodyPart
    partComposition: Organic
  - type: Woundable
    damageContainer: Biological
  - type: WoundableVisuals
    thresholds: [ 65, 65, 65, 65, 65, 65 ]
    occupiedLayer: Groin
    damageOverlayGroups:
      Brute:
        sprite: _Shitmed/Mobs/Effects/brute_damage.rsi
        color: "#FF65"
      Burn:
        sprite: _Shitmed/Mobs/Effects/burn_damage.rsi
